### ISSUE TITLE
Overview and direction

### ISSUE THREAD

**Issue by Mesuva** [concretecms-community-store/community_store#1]
(I've moved much of below to the roadmap section of the wiki - https://github.com/concrete5-community-store/community_store/wiki)

Here's a rough 'roadmap' as to where I think Community Store needs to go.
However, let me stress that this project is intended to be completely community driven, so it's really just a suggested list.

I think the goal should be to keep the 'core' of the store as lightweight as possible through the use of Event hooks and a well rounded API.  If a feature is something that is less commonly found in online shops, it's perhaps best to be developed as a separate add-on (which can then be stored within this github organisation as well).

Right now the shop is quite stable, but there are some aspects that would benefit from more testing:
## Immediate testing required
- [x] Real-world test of Paypal (hasn't been done for a while, this is now a separate add-on)
- [x] Digital Downloads may still have some permission issues 
- [ ] Setups that create new user accounts and add user groups would benefit from further testing.
- [x] Check management of order statuses/histories. Someone may be able to comment on whether this is the best way to manage these status
- [ ] Shipping methods in general would benefit from validation testing
## Priority development (not required to have a fully functioning shop but expected features)
- [x] Additional Order attributes - currently being worked
- [x] Layout of product, product list block add/edit interfaces, add tabs or at least two columns
## Recently completed development
- <del>Disable shop option (Adding to cart and ordering enabled, Ordering disabled, Catalogue mode)</del>
- <del>Sorting of product lists in dashboard</del>
- <del> Save on product, return to current tab, same with settings page</del>
- <del> Update product block to have google metadata (may need a sitewide currency config setting)</del>
- <del> Convert Payment methods to Doctrine saving</del>
- <del> Duplicate product button</del>
- <del>Add shipping method to order emails</del>
- <del>Add payment method to order emails</del>
- <del>Ability for single shipping methods to return multiple options</del>
## Important complex development (future work based on feature requests and discussion)
- <del>Discount codes should be able to be directly entered on checkout screen</del>
- Data export CSVs - separate package?
- Replace all manual SQL queries with doctrine equivalents - almost there?
- Translations need updating
- <del>Related products panel/block</del>
- Check for any payment methods before deleting package (ask them to be deleted first)
- Integration with - https://www.easypost.com/ ?
- Product option set (pre configured options)
- Product Filter (sidebar)
- Develop SASS/LESS files for core shop output
- Move cart to database, for recovering carts, perhaps both, needs discussion
- Swap to using thumbnail from file manager for lists?
- Associate logos with shipping methods (useful ?)
- PSR-2 for all code

**Comment by rii-J** [comment]
Hey, we are using the community store for the first time for a client, and those all the improvements we are doing right now, so may be some of them can be commited
- Create a PDF File for Invoice with a different incremental Invoice number then the Order Number. (The invoice should only be created when the Order is accepted / validated or paid(already impemented) what do you think?
- Buyer infos should be coming from the attribute sets (Store.user-info / Store-shipping-info, store-delivery-info)) (already implemented) so when adding a new field to the set this will be shown in the checkout form 
- Validation of Address fields separately, we've made a pull request to the core so may be this will be a nicer solution : [https://github.com/concrete5/concrete5/pull/3993](url)
- a cleaner Order-Slip that opens the printpopup of the browser  (implemented already)

**Comment by Mesuva** [comment]
I'm certainly open to extra features like this.

With the the buyer information, additional order attributes have recently been implemented, but they're really just in their own part of the checkout - it would be nice to be able to add further attributes specifically to the billing or shipping set of fields. 

Quite a long list of improvements have been merged into master in the last few days, so it's worth checking out those changes if you haven't pulled down a copy for a while.

**Comment by hurtlecreative** [comment]
Hi Ryan, I see '_Discount codes should be able to be directly entered on checkout screen_' crossed out in '_Important complex development_'... Is this something being considered?
I've been looking for a gift card/promotional code solution, and hoped the '_Gift card payment add-on_' by Revolve 314 Digital would fit the bill... https://github.com/Developer314/community_store_buy_gift_card
However, you can only use a code as a payment method (for a product+shipping equal to or less than the value of the voucher), rather than what you mention above.
Appreciate your thoughts on this... would be an excellent feature!

**Comment by Mesuva** [comment]
Whilst that list is arguably a bit old now, if it was crossed out it means it was actioned in some way.
Nearly all of the things not crossed out on that list have actually been addressed, this thread either needs closing or updating.

There is a way in both the cart page and checkout page, to enter a discount code and apply it. I think that's all it was referring to.

Gift cards are really quite a tricky thing to handle, as they're quite different from a discount really.
A gift card had to be registered _somewhere_ and then its current value tracked.
And then in the checkout, it's not really a discount being applied, it's _credit_ to be applied against the invoice.
That's why I think the add-on you've linked works as a payment method.

The closest thing in Community Store right now to gift cards is the ability to have discounts that apply a fixed amount discount, rather than a percentage.  Those can be single use, but it doesn't handle cases where someone might have  $50 gift card, but they use it to buy $25 worth of stuff.. the other $25 is effectively lost. I wouldn't be happy with that if that was my gift card...

As we don't have a way to have multiple payments types pay for an order I unfortunately don't think there's an immediate solution for this.

**Comment by hurtlecreative** [comment]
Thanks for the explanation! In that case, I'll go down the discount code route... thanks again 👍

**Comment by JeffPaetkau** [comment]
> The closest thing in Community Store right now to gift cards is the ability to have discounts that apply a fixed amount discount, rather than a percentage. Those can be single use, but it doesn't handle cases where someone might have $50 gift card, but they use it to buy $25 worth of stuff.. the other $25 is effectively lost. I wouldn't be happy with that if that was my gift card...

I needed giftcards for a recent project. When the site generates a gift card it creates a discount rule code with a fixed amount. After an order the rule is adjusted (in your example from $50 to $25) so it can be used again. After it hits $0 the rule is deleted. A bit of a hack but it works.

**Comment by Mesuva** [comment]
@JeffPaetkau that's very clever, and actually quite simple logic wise. An option to behave that way might be worth adding to the core of the system...
