### ISSUE TITLE
Global option groups

### ISSUE THREAD

**Issue by lvanstrijland** [concretecms-community-store/community_store#124]
When I added an option group to a product with some options.
I duplicated the product and the groups where successfully copied.
But when I add a new option to the option group, this option won't be added to the other products with this option group.

It might be a good feature if there were global options groups that can be selected by a checkbox for each product.

**Comment by Mesuva** [comment]
I've seen others commenting about a feature like this.

I can see the benefit of something like a option group 'preset', so something like a list of standard sizes. I could imagine something like t-shirt shop, where nearly all t-shirts have a set of mens and womens sizes, so it would be a big time saver every time you add a new product, to be able to pick from a list of presets and have it automatically add in the list of options.

But I'm having more trouble thinking of a scenerio where you'd want to have more of a global set of options, where if you added an option to it it would add it to _all_ products that share that option group. Can you give me an example type of product where this would be needed?

**Comment by lvanstrijland** [comment]
Well for example I would create a webshop for candy.
So there are lollipops with different colors, flavours.
There are also different sizes. for each size we create a new product.

The color and flavour options are the same for each product so it should be possible to select the global colors and flavours options (i.e. by selecting checkboxes).

But there still need to be an option to create specific option groups for products.
In this way it is still possible to use different colors or flavours if you would like to.
In this case you remove the check for the global option group and use the specific one.

**Comment by JohntheFish** [comment]
I think this comes back to the concept of product types as discussed in the forums. What @lvanstrijland describes is a store containing a single product type.
https://www.concrete5.org/community/forums/5-7-discussion/ecommerce-solutions
