### ISSUE TITLE
Opening an order the fulfilment text is reset to default

### ISSUE THREAD

**Issue by Babinsky** [concretecms-community-store/community_store#142]
Hi
In the Admin - Store - Orders view I open an order to update the fulfilment status.
Upon opening, the fulfilment status is always set to default (first in list, in my case Awaiting Processing), even it had already a different status (like Shipped).
Regards

**Comment by Mesuva** [comment]
Do you mean in the drop down select? 
That's not going to indicate the current status, it's only used as a selector to set a new status

**Comment by Babinsky** [comment]
Assuming that if I have the status shipped, that I see the current status (e.g. shipped) and then being able to choose the next status from drop down.
<img width="1235" alt="screen shot 2016-11-30 at 10 16 07" src="https://cloud.githubusercontent.com/assets/2919631/20746576/9f19b0f2-b6e6-11e6-9ca2-8bd881f72ed6.png">
<img width="536" alt="screen shot 2016-11-30 at 10 17 01" src="https://cloud.githubusercontent.com/assets/2919631/20746580/a3ceed38-b6e6-11e6-843b-a693e9521e63.png">

**Comment by Mesuva** [comment]
This isn't a bug as such, but I agree that it would make sense to default the selector to the next status (instead of having to pick it).
