### ISSUE TITLE
[Announcement] - Community Store is now at version 1.0

### ISSUE THREAD

**Issue by Mesuva** [concretecms-community-store/community_store#151]
I've just made the call to increment Community Store to version 1.0 based on a few reasons:

- Overall there are no obvious features missing from the store, there are features to handle most small to medium online shops
- There now should be 100% compatibility with v8.0.1
- The order process has been reworked, a long standing issue
- There are currently no outstanding bugs that I'm aware of
- It's perhaps time to create some releases and a little more awareness of the project
- I'm starting to run out of 9s..

Soon I'd like to make a roadmap of what features I personally think should be tackled next, keeping ambitions achievable and the codebase stable.

I'd also like to do a video outlining some of the more interesting features that have been added lately.

Thanks to everyone who has been helping out!

**Comment by typoman76** [comment]
Thanks Ryan for managing and pushing this forward!

**Comment by appliculture** [comment]
Thank you so much Ryan for your great work. You've done a fantastic job on this add-on also by adding many functionnalities and fixes that wasn't a need for your personal projects.

Long life to Community Store!

**Comment by Mesuva** [comment]
Here's a rough outline of what I'd suggest as a development roadmap. The numbers are more to show that I'd show each as a significant, and the order is just a loose suggestion. 

Obviously we could list an enormous list of ideas and possible features, so I've tried to list items here that are reasonably achievable, with many of them items that others have mentioned as 'must have'.

1.1 - Inclusion of VAT option
1.2 - Product list sort dropdown (sort by name, price, etc)
1.3- Address issue with variation data clearing when options change
1.4 - Multilingual support focus, storing language against order for emailing
1.5 - Aim to include filter/search functionality submitted by datasouth
1.6 - My Account Area (list of orders and statuses), Customers section in Dashboard
1.7 - Better shipping integrations?  (might be just extra packages)
1.8 - Discount enhancements - add options to filter by user group, product set, product, category(?), tiered pricing?
1.9 - Display of category product totals on autonav
2.0 - Rework of order/product attribute related code, removing deprecated functions

Other related packages
Around 1.3 - Authorize.NET support
Product/Order export functionality package

**Comment by JohntheFish** [comment]
I have been kicking around the idea of porting Zone Based Shipping and am encouraged by the way Community Store has been developing. (I looked into doing so way back when Vivid commerce was released, but the code was too buggy. At the time concluded I would end up doing store support rather than supporting my product.)

Concerns:
- How much need is there for shipping decisions more complex than Community Store already bundles?
- Is the market big enough to make it worthwhile?
- Would the market for ZBS be undercut by similar (and free) future developments of Community Store?

**Comment by MichaelMaar** [comment]
@JohntheFish Your point number 1. I can see a lot of places where more complex shipment methods would benefit Community Store. We do already have a DHL shipment method that we feel that should go commercial. your point number 2 and 3. I have been thinking a lot about this lately. We have some add-ons for Community Store that we would like to sell. But because Community Store is not on the marketplace, it is somehow difficult. The big question here would be if add-ons could be approved by PRB?

**Comment by JohntheFish** [comment]
There is no reason addons for Community Store can't go through the PRB to the marketplace. Amongst the PRB we have discussed just that and agreed in principle. 

In the past we had a lot of issues with addons submitted for Vivid store not working because of bugs in the underlying store, so their path through the PRB stalled at that point (and Vivid store is in the marketplace). Community Store is a more mature and developed package.

The hazard for developers is there is no marketplace support for Community Store, so customers would buy an addon, perhaps get stuck with Community Store, then assume the addon developer would support them through that as well as through the developer's own addon. While declining to provide such support would be legitimate, it can easily result in upset customers, refund requests and poor reviews. 

It would be a lot easier if Community Store itself was in the marketplace, so there were fixed release points and a support channel.

**Comment by MichaelMaar** [comment]
But who should stand behind this support. I would not ask @Mesuva to do that, that would not be fair. Do the technicality for multi user support panel in concrete5.org already exists? Or do you have any suggestions on how to manage this form of support?

**Comment by JohntheFish** [comment]
Agreed, but I don't have a solution, and that is where the whole problem lies.
Its fine for those with good developer skills, but anyone hoping to just plug it in and go is not in an ideal situation if their business depends on an eCommerce site.

**Comment by MichaelMaar** [comment]
I could offer a demo/support site on Concrete5 Denmark's hosting servers (they are actually placed in London). Would that be an idea?

**Comment by jasteele12** [comment]
I think multiple people/companies being able to offer support contracts would be a good thing to have. More choice for customers and another possible income stream for concrete5.org

**Comment by Mesuva** [comment]
@JohntheFish I doubt anything in the future will be added to Community Store that would come close to the complexity of your existing ZBS add-on.

I've got a simple zipcode matching shipping calculator that I'll likely add to github at some point, even for something simpler like that I see as better off being separate to the main store code in case it needs to be customised. 

In terms of a market for paid complementing add-ons though, I'd say there isn't one yet. We're using community store for our own clients and I am speaking to others about custom uses for it, but I'm not seeing a broader demand at this point. That may be because this project simply hasn't been promoted and is only really now becoming stable. (or maybe that's just me, hard to say)

Our own need for Community Store has been, and is likely to continue to be more technical in nature, as our projects nearly always have unique requirements and customisations. That's also the same reason why we use concrete5.

I'm going to be biased with my view as our business is generally about building complete sites and offering custom programming. Some might really be attracted by the idea of having community store in the marketplace and being able to offer hourly support for common problems, but for us that's just not our business model. 

I appreciate though that a lot of concrete5 users may have the desire to have a marketplace version of the store they can just click to install and be running in minutes. In terms of offering additional free/paid add-ons for the store, it would certainly make things easier if the store was a supported marketplace add-on too, but as it's been said, the issue of who actually who then would support the add-on is the big question. 

The other concern is that community store is still fairly new, so there's likely to be a lot of changes over the next year that may or may not work completely cleanly across upgrades. Obviously I'd love for all updates to just work, but as an example, the attribute related code in the store will need to be updated at some point to the v8 way of working (and it's legacy/deprecated), and in doing so it _might_ remove 5.7 compatibility. I'm not even sure if that work would be able to be done and allow stores to be upgraded. 

So I'll personally just not want that liability in the marketplace - push an update and boom, hundreds of sites have problems. With simpler add-ons in the marketplace there's enough predicability, but with something as big as the store I think it's a huge concern, especially if it's offered as a free add-on. 

I'll admit that (rightly or wrongly) I do have a view that setting up shops is more of a technical exercise and there's a bit of a threshold of web development experience that someone should meet before doing so. I'm not saying that it should be exclusively handled by developers/programmers, but that there shouldn't be an expectation that _anyone_ can set up a shop by simply clicking a few buttons on a marketplace. There are lots of DIY shop systems out there that could arguably be more appropriate for such users (ebay, Shopify, Snipcart, etc). 

I actually see it similar to concrete5 itself - you don't buy it from a marketplace and receive support with it. You either download it for free and install it yourself or you install it via a one-click installer from a hosting control. In those cases, you don't get support, you either have to work things out yourself, engage someone or ask for some community support through the forums. 

So my current preference going forward would be to:
- Keep the official source of Community Store on github, where volunteers can help with support style questions, fixing bugs and adding features. Releases can be created in github to help to indicate stable versions.
- Emphasise that this is an open source product, that you can ask for help from the broader community, but you're not guaranteed to receive it. Also, that the add-on is complex, so you should have a reasonable level of technical experience (i.e. can you manually FTP folders, do backups, install SSL certificates, understand the importance of communicating details from error messages and so on)
- I'd eventually like to see some github pages set up (https://pages.github.com/), to take the place of the wiki and be a bit more attractive/promotional. I'd love to see some videos of features, instructions, some decent doco. Some github projects have fantastic pages that feel very official.
- Ultimately it would be great if developers can advertise that they're comfortable/knowledgable in community store, in the same way they can do so with concrete5 itself, so they can be approached for more formal support contracts and development. 
- If developers want to put add-ons in the marketplace, I don't see any issue, the add-ons can refer to the community store github/pages to handle the prerequisite install. An issue with community store that affects a related add-on is not really any different than a bug in concrete5 itself affecting a general add-on in my opinion.

I'm not fixed on any of the above as such, just communicating my current thoughts really.
