### ISSUE TITLE
Installing language files

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#156]
This is an announcement rather than an issue: to download and install language files you can use my brand new [Translations Updater](https://github.com/mlocati/concrete5-translations-updater) add-on.

**Comment by lota** [comment]
Thx Michele, useful tools.

Anyway, I have a question: *.mo files could be still exists in community_store repository? and translations_updater override they?

**Comment by mlocati** [comment]
The problem with .mo files in the repository is that you have to keep them up to date manually.
That involves downloading the .po files from Transifex, and compile them to the .mo format with the `msgfmt` gettext tool.
That's the reason why I suggested #145 and made The Translations Updater publicly available

**Comment by Remo** [comment]
I support this and I'd also support a PR against the core to include that updater there. There are still a lot of beginners for outside the US that will have a hard time, or at least a long time, till they figure out where to get translations from.

**Comment by mlocati** [comment]
> a PR against the core to include that updater there

I'd like to switch from the current system (Transifex ⇆ @Remo's server ⇆ GitHub repositories) to [Community Translation](https://github.com/concrete5/addon_community_translation) before doing that (it'd simplify everything and would offer translations for all the packages in the concrete5 marketplace)

**Comment by Mesuva** [comment]
A quick question from me - when I put together a release and upload it here to github, should I be looking to collect and include the language files? 
Or is the idea here that you never bundle language files in any regard and they should always be downloaded (and perhaps updated) as a separate activity?

**Comment by mlocati** [comment]
This is not a decision that's up to you :wink:
You could prepare an archive with the most translated languages (saves users some time), or you tell the users to install Translations Updater (saves you some time).
