### ISSUE TITLE
Add product block programmatically

### ISSUE THREAD

**Issue by katalysis** [concretecms-community-store/community_store#174]
I'm trying to simplify the use of product pages in a larger Community Commerce site by adding the product block to the page template programmatically.

I'd expect it work something like this but it doesn't.  Should I expect this to work?

```
<?php
$product = BlockType::getByHandle('community_product');
$product->controller->productLocation = 'page';
$product->controller->showProductName = 1;
$product->controller->showProductDescription = 1;
$product->controller->showProductDetails = 1;
$product->controller->showProductPrice = 1;
$product->controller->showWeight = 1;
$product->controller->showImage = 1;
$product->controller->showCartButton = 1;
$product->controller->showIsFeatured = 1;
$product->controller->showGroups = 1;
$product->controller->showDimensions = 1;
$product->render();
?>
```

**Comment by Mesuva** [comment]
Nothing immediately comes to mind why this approach wouldn't work.

What happens when you try, do you get error messages or just no output?
Have you tried putting some debugging statements within the product block controller file to see how far it gets along, whether it finds the product, etc?

**Comment by cahueya** [comment]
I've found that the product list block does not show anything when put on a page and told to retrieve the products from below that page (after moving the product in the sitemap of course).

**Comment by katalysis** [comment]
I believe that this will only show products if the category page is a designated category in Community Store and has products set up in the Product > Categories tab.

This raises an interesting issue, I would prefer to arrange my products as pages in the sitemap as noted in #175 rather than storing all pages under a single Products page and using the Community Store categories system.

It would be great if the product list block could accommodate this and allow products to be selected either from 'Under current Page' (meaning product pages actually located beneath the page) or  'Under current Category' (meaning located using the category system).

**Comment by Mesuva** [comment]
@katalysis I was just about to suggest such an option. I think the current options in the 'List Products' drop down could be better described to avoid this current confusion. Perhaps it should be worded more like 'Categorised under current page'. (or your wording may be better as it's simpler)

Then further options could something like 'With a product page under current page'. 

I think if someone tackles this extra option it should be in conjunction with the option we discussed here: https://github.com/concrete5-community-store/community_store/issues/175
