### ISSUE TITLE
Community Store Reviews package

### ISSUE THREAD

**Issue by wardhache** [concretecms-community-store/community_store#178]
I've created a new package for Community Store to ask for customer feedback on the products.
This package adds review capabilities to your store.
Link: https://github.com/webhapp/community_store_reviews

Short description
- Ask for submitting a review on a product-page.
- Send a review reminder mail when an order is completed (automated job).
- Custom page to review the products of an order after the reminder mail.
- Create custom ratings for your reviews.
- Auto Approve reviews.

Please test first before using in a live environment.

**Comment by Mesuva** [comment]
Nice one!  Will have to check it out soon.

Does it have a particular license?

**Comment by Haxe93** [comment]
It has no particular license.
I am now running several tests again to make sure it all works properly.
If you find any issues, please comment below or add it to the issues on my repository so I can solve them immediatly. 

Thanks! I hope you all like it.
