### ISSUE TITLE
Payment method on permission

### ISSUE THREAD

**Issue by cahueya** [concretecms-community-store/community_store#202]
I had a thought about how to refine the payment process for needs that I faced with other shops and I believe it would be useful to filter payment possibilities based on user permissions.

For example:
If I have a shop that sends out goods I would rather not offer purchase on invoice to unregistered guests or unvalidated users. In that case, I would want to force "guests" to use paypal or any other payment processor that helps with security and validation of the payment. But if someone is a known customer and/or registered with a full data set, sending an invoice will be fine.

or:

If I have the case of rare cash payment ("pick up your order"), I would not want to offer "cash" as a payment method for anybody but I'd like to have it available for myself to keep up with the order numbers....

Whatdoyouthink?

**Comment by Mesuva** [comment]
Sorry, I think I originally missed this. 
I think this would be handy for cases where customers have an 'account' with a shop, meaning that they are allowed to place an order using something like the Invoice method.

So I think this would be handy, but I think this would take quite a fair bit of work to code up.
