### ISSUE TITLE
Feature: File Attribute support on Orders or Products

### ISSUE THREAD

**Issue by wishborn** [concretecms-community-store/community_store#224]
I've added a file type attribute to the Order and it shows up as intended during checkout, but when the click the Next button nothing happens. I get no error from c5 but I do get this error in the js console. This result is persistent across config options for Guest/No Guest/Signed In and HTML Selector/c5 File Selector.

Uncaught TypeError: Cannot read property 'replace' of undefined
    at HTMLDivElement.<anonymous> (communityStore.js:399)
    at Function.each (jquery.js:2)
    at m.fn.init.each (jquery.js:2)
    at HTMLFormElement.<anonymous> (communityStore.js:396)
    at HTMLFormElement.dispatch (jquery.js:4)
    at HTMLFormElement.r.handle (jquery.js:4)

**Comment by Mesuva** [comment]
This might be able to be solved with an improvement around that line 399 of communityStore.js

Could you try it with this instead:
```
$("#store-checkout-form-group-other-attributes .row").each(function(index, el) {
            var akID = $(el).data("akid");
            var value = $(el).find(".form-control").val();
            if (value) { 
                        $('.store-summary-order-choices-' + akID).html(value.replace(/[\n\r]/g, '<br>'));
                        $('#store-checkout-form-group-payment').append('<input name="akID[' + akID + '][value]" type="hidden" value="' + value + '">')
            }
        });

**Comment by IdeaSponge** [comment]
That got rid of the JS error and allowed the order to be processed to completion, but I'm not sure if it saved the uploaded file. Looking at the code for displaying Other Choices, I can see it only supports number/string display values. I checked the File Manager to see if a new file was there but there was not. Any suggestions?

Side note: This package is a great package btw and thank you and the other contributors for keeping it current and free. Any plans on adding Express support in the future?

**Comment by Schnak** [comment]
Any news of this improvement ? I need too a file upload for an order for customer

**Comment by Mesuva** [comment]
This was developed to handle this: https://github.com/concretecms-community-store/community_store_file_uploads
