### ISSUE TITLE
Product List Block

### ISSUE THREAD

**Issue by necaustralia** [concretecms-community-store/community_store#244]
I was after any guidance/documentation with regards to adding custom attributes to the product list block. Kind of like the data formatting tab on the C5 ecommerce add-on https://www.concrete5.org/marketplace/addons/ecommerce/documentation/operator-s-guide/product-list

**Comment by Mesuva** [comment]
Outputting additional product attributes is going to be handled by custom block templates

I'm pretty sure you can just go:  
$attrvalue = $product->getAttribute('att_handle');
to fetch the attribute, then you can output however/whereever you need. It should be very similar to page attributes.

**Comment by teknoziz** [comment]
Does this still hold true? I want to list my attributes on the Product List block.

**Comment by Mesuva** [comment]
Yes, should be the same

**Comment by teknoziz** [comment]
Could you tell me how to list a file attachment?  This is not working for me...

`                    <?php if ($attrvalue = $product->getAttribute('msds')) {
                        ?>
  						<div><b>MSDS</b></br><?php t($attrvalue); ?></div>               
                          <?php
                    } ?>
                  
                    <?php if ($attrvalue = $product->getAttribute('specifications')) {
                        ?>
  						<div><b>Specifications</b></br><?php t($attrvalue); ?></div>               
                          <?php
                    } ?>
`

**Comment by Mesuva** [comment]
Try something like this:

```
<?php
$file = $product->getAttribute('msds');

if ($file && $file->getFileID()) { ?>
    <a href="<?php echo  View::url('/download_file', $file->getFileID()) ?>"><?php echo $file->getTitle(); ?></a>
<?php } ?>
```

If you wanted to force the download, replace `'/download_file'` with `'/download_file/force' `

**Comment by teknoziz** [comment]
Perfect, thanks!
