### ISSUE TITLE
Tax adding crazyness

### ISSUE THREAD

**Issue by cahueya** [concretecms-community-store/community_store#254]
This is more like a feature request or a wish:

Right now adding taxes can be a very time-consuming thing. Like if the shop is sitting inside the EU, the rules are: 

for ALL inside EU countries excluding your own: apply VAT based on billing address, allow deactivation of VAT of number included

for your own country inside EU: apply VAT based on billing address, no deactivation possible

for all other countries in the world: apply VAT based on billing address, no deactivation possible

most EU countries have at least 2 tax rates, so this means setting up 2 tax rates for every possible customer country in the world... urghs.

Could there be an easier way? Like a prepared list template or something?

**Comment by Mesuva** [comment]
That sounds horrible. Move to a different country perhaps?  :-)

Could you envisage a user interface that would solve this problem, some sort of grid entry perhaps?

**Comment by cahueya** [comment]
First thing i taught about was a db-table that could be imported. But the flat shipping rate interface (CSV-import) would work better for most people.

But of course, a interface-thingy would be great.


So to keep it EU-wise simple:

1. Checkbox 'Is your shop inside the EU'
2. Select 'Choose your home country'
3. Define tax rates / classes

Boooom magic:

Every country in the world outside the EU has magically applied the VAT and no chance for tax exemption - every country inside the EU has applied VAT with the possibility of tax exemption but your own cannot. 

rule-wise it looks pretty simple :)

**Comment by cahueya** [comment]
Oh, one more rule missing: There is one special class of products (digital goods) where another rule applies: The tax rate depends on the location of the recipient.

So if I am selling FROM italy (20% tax) TO Austria (22%), and the product is a "digital good" it will be charged with 22% tax.

This is called 'reverse-charge' and is only in law since 2015.

**Comment by Mesuva** [comment]
<head explodes>

**Comment by cahueya** [comment]
But I'd say - setting up such little 'special rules' rules that apply only to the EU countries is easy to be done by hand. When all the other stuff ('world') is already  defined.

**Comment by cahueya** [comment]
Look:

https://github.com/yireo/Magento_EU_Tax_Rates

**Comment by Remo** [comment]
not sure if you've seen this https://github.com/concrete5-community-store/community_store/issues/108

**Comment by Remo** [comment]
There are a lot of libraries dealing with this,  here's one I've used before https://github.com/dannyvankooten/vat.php

**Comment by cahueya** [comment]
Crazy, he read my thoughts before I had them :-)

Thank you, that's exactly the right track!

**Comment by vvinci00** [comment]
@cahueya I'm having the same issue..
ecommerce in Italy and sell to Italy and EU.

Did you have integrated the library (https://github.com/ibericode/vat) in some way?

at now, as per CommunityStore works, if some one enter a VAT ID, then the Tax has not been applied in any case but it's wrong.. the TAX should not be applied only if the entered VAT ID is different from the country of ecommerce eg. I'm in Italy:
- If I sell to Italian customer, I have to apply the TAX
- if I sell to France, Germany, EU State, I don't have to apply TAX
- if I sell to state outside EU (Switzerland, GB, ...) I've to apply a different TAX
