### ISSUE TITLE
Event Booking for Core Calendar

### ISSUE THREAD

**Issue by pinecreativelabs** [concretecms-community-store/community_store#339]
Concrete 8.3.x now has the Calendar addon included in the core. It doesn't seem like there is a way for users to register for event, and it would be nice to have a way to charge for registrations. So, I think this would be an ideal addon idea for Community Store. Thoughts?

**Comment by drumrby** [comment]
I am wanting to do this exact thing. I want users to be able to register for an event, and mark events as free events or paid events, and handle paid events through Community Store.

**Comment by justynpride** [comment]
I’m in agreement. I’ve had a few thoughts and discussions about community store and tickets. Nothing has come to anything as yet. You’ve got an agreement from me for this suggestion.

**Comment by Mesuva** [comment]
I've not used the new Calendar in v8 in production yet, I've only had a short play with it, and we've got our own event calendar package we use for such purposes.

Hooking up products to events is actually something we've done before, but we didn't need an extra package. There are a few different ways to do it, here's one way that requires very little coding:

- Create an event, with one or more days/times, making the event create an event page that can be clicked through to. Maybe categorise the event as well
- Create an event product either per event time (if limiting numbers and tracking ticket holders is critical), or one event with multiple options for each time. I suggest putting the event date/time in the product name 'Karnivool - 5th February, 2018 - General Admission'
- Customise the event page template, adding in an area (potentially a global area) and place a Product List block and set the List Products setting to 'Under Current Page'. The 'Add To Cart Button Text' could be changed to 'Add Ticket(s) to Cart' or similar to make it clearer
- Finally on the product, _Categorise it under the Event page_

What happens then is that when you click through to an event, you get a list of products (tickets really) for that event, and if there are multiple dates and/or types they'll show up in the list. It then it pretty easy to customise the display of that particular list of products with a custom template.

With this set up, there's really only one step to associate a ticket product with the event - just categories it under the event page. 

From a customer's point of view, their order receipt can clearly indicate the date and time of ticket they have purchases (as long as that's in the product name or as the product option).  The shop admin can also go to the reports section, for Products, and view a list of purchases of that product/event, along with emails, phone numbers and the number of tickets. Print that list and you have a door list.

We've done the above on a few sites (or at least a very similar approach) and it works well. One further aspect might be changing the label of the link that views the Event page from something like 'View Details' to 'View Details and Buy Tickets', if that event has associated ticket products. That's really just a case of an attribute or some other flag on the event to make it display slightly differently.

What I'm not sure on is if there are aspects to the built in calendar which make the above setup awkward, I just don't know it that well. But the above is a pretty generic way to tackle it - I'm not sure what else would be needed.

**Comment by jjojr** [comment]
I implemented the C5 event calendar in version 8.5.2 for a non-profit website.  We put events on the calendar where therapy dog team visit venues.  The events are the equivalent of an appointment where the therapy dog teams are the customers who confirm they will attend that appointment.  A link in the event that connects to an appointment/reservation function might be a good starting point.
