### ISSUE TITLE
Discussion: Keep items in basket for longer

### ISSUE THREAD

**Issue by madesimplemedia** [concretecms-community-store/community_store#342]
Hi, I have a customer who says items only remain in basket for 20 mins.
Is there a way to control how long they are kept in the basket?  Ideally he wants 48 hrs.

**Comment by AdamBassett** [comment]
The 20 min limit is a session time out controlled by PHP.  You don't want to increase this for security reasons, and in a lot of cases host companies wont increase this time limit.  There are other ways to increase this time but at the moment I don't believe any of them are implemented into community_store.

If you are looking for a how.  The way I know, is to make your own cookie and set the expiration X hours out. In your case 48 hours. Then when the cart is requested if there is no session, but there is a cookie,  make a new session and pass the cookie info.  This will keep the cart loaded as long as the cookie has not expired.  

Note that each time the cart page is requested the cookie would be rest.   So if the user returns to the cart each day the cart will never empty.

**Comment by typoman76** [comment]
I have the same feedback from some customers on my first shop I made. Has anyone done this cookie solution? Seems helpful for not loosing cutomers. 
In our case the user was on the checkout page on the payment provider. An just then the cart was empty and no amount was passed to the payment-provider. So I didn't get an order but got a complaint ;-)
