### ISSUE TITLE
Deleting packages requiring community store , deletes CS doctrine proxies

### ISSUE THREAD

**Issue by Jozzeh** [concretecms-community-store/community_store#347]
Hi,  
User Rosie607 reported this error with packages requiring community store.  

> So I've done this a couple of times now and it's happened both times, if I uninstall this package it also deletes a bunch of files from the folder /application/config/doctrine/proxies/ that are needed for the rest of the community store package.
This makes the whole community store package / any page with a community store block on error.

> this also seems to be happening if I uninstall another package. I tried uninstalling the Tiered Shipping Package and the same thing happened it also removed all the Community Store files from the proxies folder.

see : https://github.com/concrete5-community-store/community_store_abandoned_cart/issues/3

I think it might be an issue of Concrete5 itself, but I'm not sure.

**Comment by Mesuva** [comment]
That's a weird one, but I can't think of when i've recently uninstalled a community store package.
I'll give it a test myself when I have the chance

What is strange is why it would remove those proxy files when they aren't at all defined within the 'child' package. 

I think a temporary fix would be to go to visit /index.php/dashboard/system/environment/entities/view and hit the red 'Refresh Entities' button, but that shouldn't be necessary!
