### ISSUE TITLE
Feature Request: Sale Price Date Selectors

### ISSUE THREAD

**Issue by drumrby** [concretecms-community-store/community_store#404]
I would like to be able to set a date for a sale price to expire. I see it as being a date selector just below the sale price field that, at least expires the sales price on that date. Ideally I see it as being two date selectors, one that is the sale start date and the other is the sale end date, so you could program in a sale ahead of time.

**Comment by justynpride** [comment]
My two cents on this would be whether this kind of feature could be expanded to allow for multiple discount dates. This is helpful for scenarios where prices for items/tickets can vary depending on when purchased. So $100 if purchased before 1st March, $125 before 1st April, $140 thereafter. This can be achieved using multiple products, but if you want to control numbers of the same product sold keeping the same product is best.

**Comment by Mesuva** [comment]
Yes, we've had to do 'early bird' pricing a few times on sites with tickets, something to adjust the pricing based on date ranges would have been very handy. Will give it some further thought.

**Comment by justynpride** [comment]
Thanks for considering it. Anything that can give more than one price break options would be amazing.

**Comment by JeRoNZ** [comment]
I note that in CS 2.7.1 (and likely earlier versions) there is now a pair of date fields to restrict the sale price's effect.

I've also just noticed that the product list class doesn't respect those dates, so the product continues to show as being on sale when it isn't.

**Comment by JeRoNZ** [comment]
https://github.com/concretecms-community-store/community_store/pull/897

**Comment by Mesuva** [comment]
Gotcha @JeRoNZ , and thanks for the PR!
