### ISSUE TITLE
Setting prize (Thousands Separator to "." and Whole Number Separator to ",") and then write a prize "18,50" in a product failes

### ISSUE THREAD

**Issue by MichaelMaar** [concretecms-community-store/community_store#418]
In Denmark we have (Thousands Separator to "." and Whole Number Separator to ","). That works good enough. But when I then go to a product and write "18,50" I get a problem. the 18,50 is translated to 18.00.

I have even one time seen a whoops error on that (but I can't remember what it said).

Is there any way around this?

**Comment by Mesuva** [comment]
I've updated the way that prices are formatted in the latest master, this _may_ have addressed this particular issue.

But my impression of this is that's about entering the value with those separators in the first place and how it saves down. Happy to discuss further.
