### ISSUE TITLE
Tax Exemptions for Non-Profits

### ISSUE THREAD

**Issue by pinecreativelabs** [concretecms-community-store/community_store#427]
I have a prospective client who was wondering about tax exemption during checkout. They have some customers who are non-profit, and they would like to offer some option for tax exemption. How could this be done?

**Comment by AdamBassett** [comment]
You could over ride the ```getTaxRates()``` in ``` src/CommunityStore/Tax/Tax.php``` to look and see if the user is part of a group and if so return early an empty tax array.   This would require that your non-profits have an account on the site and some one would need to vet each account to make sure this is not abused.

I did this in a fork for a wholesale option for a client.

The other option would be to build a discount code that removes the tax and give that code to the non-profit.  This has security issues though.
