### ISSUE TITLE
Shipping Fee Per State

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#529]
Is putting something in place to charge different shipping rates per state? We have a few very heavy items (800 pounds). The shipping costs to a near by state is about $600, but across country would be $1,100.
I thought about using a tax fee and call it a shipping fee, since it a percentage I don't want it based on what they spend, but more on how much shipping is or a flat fee, I can change those per state.

**Comment by Mesuva** [comment]
When we're applying different rates based on states, whilst still keeping existing shipping calculations in place, we're getting to some quite complex shipping rules - it's either a case of developing a new shipping method that factors in all the different aspects to this, or using something like the EasyPost method to actually calculate the true shipping cost. 

I see you were trying to add another EasyPost shipping method (and hit that saving issue) - was that in attempt to address this scenario?

**Comment by mdius** [comment]
No, the EasyPost issue is that the UPS rates seem accurate, but the USPS seem very low, so I wanted to make an EasyPost shipping mod for UPS and USPS so on the USPS I can add like 20% to make the sipping cost more accurate.

I think to solve this particular issue is to only do a quote on there products, probably the safest way to handle this.
