### ISSUE TITLE
Product variations hard-coded to maximum of 50

### ISSUE THREAD

**Issue by markbennett1973** [concretecms-community-store/community_store#569]
I can understand the need for a limit on the maximum number of product variations (e.g. exceeding maximum number of inputs when posting the product page), but we need to support more than the hard-coded limit of 50. Could this be changed to a config setting instead, with a default of 50, so we can override if required?

**Comment by Mesuva** [comment]
I'm quite open to this being configurable, it makes a lot of sense.

I think it held off doing this after adding the ability to remove options from being part of variations, whilst still being able to adjust the price. My thoughts were that if you had that number of variations that there's a strong likelihood that products should be managed a differently and split up... but everyone has different use cases!

I'm naturally open to a pull request on this, or I can add it to my todo list (which I'll be looking at soon-ish)

**Comment by mlocati** [comment]
This has been already implemented in #680, isn't it?

**Comment by markbennett1973** [comment]
Yeah - looks like it. Thanks to everyone who got that one written, tested and merged 👍
