### ISSUE TITLE
Question: Integration of Dropshipper

### ISSUE THREAD

**Issue by krebbi** [concretecms-community-store/community_store#588]
Hi Folks,

how effortful do you think would be an integration of a dropshipper API like this:
https://www.bigbuy.eu/en/api_bigbuy.html

I'm just curious if it's better to go with shopify or integrate it into the (more loved by me) community store?

Cheers

**Comment by Mesuva** [comment]
My initial thinking would be that it would be a very large undertaking to integrate the two. 

If something like Shopify is an option, I'd be weighing up the ongoing costs against a rough estimate of the development work to both set up Community Store and develop a well tested integration add-on. I'd be thinking that Shopify costs would be much lower.  Keep in mind that there are ways to integrate Shopify with a concrete5 site too (we've got an add-on for this), you don't have to run a Shopify site, you'd just use Shopify's cart and checkout.
