### ISSUE TITLE
Upgraded from 8.5.1 to 8.5.4 now I get a "Call to a member function disableEnabled() on null" error

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#592]
See image for error.
Concrete Version 8.5.4
Community Store Version 1.4.7
EasyPost Version 2.1
I've had weird issues with EasyPost since I've installed it, it seems to work well, but anytime I need to update Concrete's core I've have serious issue. [EasyPost Issue #6](https://github.com/concrete5-community-store/community_store_easypost/issues/6)
So, yesterday I uninstalled it to update to 8.5.4. I upgraded with out trouble, reinstalled and set it back up. Seemed to be working, till this morning. Had issues with the shipping info loading, was just spinning the loading circle. Tried to check my "/dashboard/store/settings/shipping" and got the attached error.
Cleared cache and that worked to at least load the shipping info at checkout. But still getting the "disableEnabled" error in the setting/shipping.
![Concrete Error](https://user-images.githubusercontent.com/28864099/101776076-648b9a80-3abe-11eb-90c8-1eacee9e67a0.png)

**Comment by mdius** [comment]
I also refresh the "/dashboard/system/environment/entities" with no change to the error.

**Comment by Mesuva** [comment]
I'm suspecting that the uninstall and reinstall has left some entries in the database that should have been cleared up.

What is in these two tables: CommunityStoreShippingMethods, CommunityStoreShippingMethodTypes ?

**Comment by mdius** [comment]
They seem to be correct.
You think I should save those tables then Delete all the entries and start over?
![CommunityStoreShippingMethods](https://user-images.githubusercontent.com/28864099/101785534-e255a300-3aca-11eb-93aa-16e0ede096d7.png)
![CommunityStoreShippingMethodTypes](https://user-images.githubusercontent.com/28864099/101785540-e5509380-3aca-11eb-987a-0341bb91bee2.png)

**Comment by Mesuva** [comment]
The other table I should have mentioned to look at is CommunityStoreEasypostMethods

**Comment by mdius** [comment]
Those I added after the update and reinstall. It was working yesterday.
![CommunityStoreEasypostMethods](https://user-images.githubusercontent.com/28864099/101792972-53995400-3ad3-11eb-9a58-c26fe63a1c63.png)

**Comment by Mesuva** [comment]
I have a feeling this was a subtle bug that has been fixed in version 2 of Community Store.

But it relates to a feature with shipping methods that was never fully realised any, so since I still had FTP access to your site I've jumped in and put a hotfix in, fixing the settings page for the shipping methods. It shouldn't be lacking any functionality because of this.

**Comment by mdius** [comment]
That seems to have cleared it up. Thank you again.
What would it take to upgrade to version 2?

**Comment by Mesuva** [comment]
Considering the size of your site, plus the number of existing orders, the challenge is making sure that the upgrade process doesn't time out, and that all the existing order and product data is retained in their attributes. 

I have done successful v1 to v2 upgrades in the past, including retaining all product and customer data, but for one I had to write some supporting code to export and re-import a lot of the data (which I still have). That fact that you are on the latest version of concrete5 makes this quite a bit easier though.

So we could look at attempting this upgrade sometime in the new year, we'd just take a clone of your site and test out the upgrade on that first. Feel free to touch base at some point.

**Comment by mdius** [comment]
I will contact you in a couple months about this to get more detail and we can go from there. I do have a cloned test site, but they don't always seem to work the same.
