### ISSUE TITLE
Display Number of products in group/category

### ISSUE THREAD

**Issue by Mesign** [concretecms-community-store/community_store#605]
Is it possible to dislay the number of product under a certain group/category? 
For example I want to display some text: "We have **#** product of **group- /categoryname #**".

**Comment by Mesuva** [comment]
Categories and Groups are quite different concepts, but you should be able to handle it in the same way using the ProductList class. You could do something like:
```
$products = new \Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductList();
$products->setCID(1234);
echo count($products->executeGetResults());
```

That should output the number of products under the page with an ID of 1234

And for groups
```
$products = new \Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductList();
$products->setGroupID(123);
echo count($products->executeGetResults());
```

Whilst that's not going be a real drain, I'd probably look to cache that lookup, so you don't have to fetch all the products every page load _just_ to work out the count.
