### ISSUE TITLE
Counting results in product list breaks when it is filtered by attributes

### ISSUE THREAD

**Issue by gregheafield** [concretecms-community-store/community_store#606]
https://github.com/concrete5-community-store/community_store/blob/a0b9cdd6d4bcd63514674f1da4bfaf6cf81bcb6e/src/CommunityStore/Product/ProductList.php#L393-L400

When you set up the ProductList to filter by an attribute, attempting to count the number of results causes an error with the attribute column not being found because the 'from' and 'join' query parts are being reset, but the where remains.

`$productList = new \Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductList();`
`$productList->filterByAttribute('product_code', "356");`
`$numMatchingProducts = $productList->getTotalResults();`

This also seems to be the same method used in the set up of the paginator on this list? For big collections, this seems to be inefficient to fetch all the models into memory?

Is there a reason this isn't just 
`return $query->resetQueryParts(['groupBy', 'orderBy'])->select('count(*)')->execute()->fetchColumn();`

**Comment by Mesuva** [comment]
That's likely to be an oversight or a misunderstanding of how resetQueryParts worked originally.
If you've changed it to just ['groupBy', 'orderBy'], and you believe everything else is still working correctly, I'm happy to accept a PR or make this update.

For the pagination, I'm pretty sure this just follows the same convention that other paginated entities in concrete5 follow. Did you have a suggestion of how this could be improved?
