### ISSUE TITLE
Composer based install

### ISSUE THREAD

**Issue by KorvinSzanto** [concretecms-community-store/community_store#635]
I've noticed this project doesn't make use of the composer based installation functionality that would allow you to install with `composer require concrete5-community-store/community_store`.

Managing packages with composer has a few benefits:
1. Concrete core dependencies and package dependencies are shared, you don't end up with two copies of things
2. Installed versions are tracked and locked and upgrading can be done just by running `composer update`
3. Vendor files don't need to be committed to git, they come in on deploy

Check out the example package here: https://github.com/concrete5/sample_composer_package I'd be happy to help any way I can.

**Comment by mlocati** [comment]
It's now possible to install Community Store (see https://packagist.org/packages/concretecms-community-store/community_store)
