### ISSUE TITLE
Update Product not saving variants checkbox

### ISSUE THREAD

**Issue by rosie607** [concretecms-community-store/community_store#645]
On the product page Options and Variants when I check the checkbox 'Options have different prices, SKUs or stock levels' and then click Update Product, the page refreshes and I get the 'Product Updated' message but the checkbox has reverted to being unchecked.

<img width="1365" alt="Screenshot 2022-01-09 at 19 52 20" src="https://user-images.githubusercontent.com/11563269/148698330-3427a4cd-652c-4e0f-8782-355f7122d333.png">

**Comment by Mesuva** [comment]
Do you have on at least one of the options you have created the 'In Variants' set to Yes?
It won't check unless you have at least one set to Yes.

**Comment by rosie607** [comment]
Ah yes that makes the check 'Options have different prices, SKUs or stock levels' box work.
I think I was finding it confusing as the options I'd set above are behaving oddly as well. On the front end it shows my three options but changing the radio doesn't have any effect. The base price is set to £10. So the first variation is added to the front end price making it £11, but changing the radios doesn't do anything, whether or not 'In Variants' is set to yes or no.
<img width="408" alt="Screenshot 2022-01-10 at 08 03 02" src="https://user-images.githubusercontent.com/11563269/148734280-07418a5d-f31b-4b20-86e4-30c55d027f32.png">
<img width="389" alt="Screenshot 2022-01-10 at 08 03 06" src="https://user-images.githubusercontent.com/11563269/148734283-bcfb215f-94bc-4f72-851c-53632a95ca46.png">

**Comment by Mesuva** [comment]
This is likely to be the same issue and solution from https://github.com/concrete5-community-store/community_store/issues/644#issuecomment-1008430066 as the issue is that the block isn't loading in all scripts.
V9 arguably isn't ready for proper usage yet, it needs a bugfix release.

**Comment by rosie607** [comment]
Thanks, I'll bear that in mind if I come across anything else :)
