### ISSUE TITLE
One Time Discount Code

### ISSUE THREAD

**Issue by craigmarcussen** [concretecms-community-store/community_store#646]
Hello,

Not an issue, but a question.

I am using Community Store (2.3.4) on a site with the PayPal payment gateway. My client would like to have a one-time discount of 15% off for a customer's first order. Since there is no login required to make a purchase, I was wondering if this is even an option. I know there is a "Single Use Code" checkbox, but this is not what I am looking for. I would need to cross-check the form info during checkout for a duplicate customer, which I am not sure is even a possibility.

Any help here would be greatly appreciated.

Craig

**Comment by Mesuva** [comment]
I think if customers aren't creating accounts the only option is the one-time codes.
And then the only way I can think of is either:
- you have a contact form, and you manually create them on demand for customers
- or, you write some sort of custom form that automatically creates one-off discounts and emails them to customers

_Something_ has to track whether it's a customer's first or subsequent order, and that is quite tricky if the same customer decides to use different email addresses...

**Comment by craigmarcussen** [comment]
Thanks for the reply.

I figured as much. Is it possible to test for previous purchases from the same email? I know that people could fake it, but it may be enough for the client.

**Comment by Mesuva** [comment]
I'm sure you could programatically check for orders, in the same way that you can search for orders in the dashboard by emails. The issue I think it more applying a discount automatically to the cart, before they're really submitted anything.

**Comment by craigmarcussen** [comment]
I agree. Wouldn't want to allow the discount, only to take it away when making the payment.
