### ISSUE TITLE
Recurring Log Error

### ISSUE THREAD

**Issue by craigmarcussen** [concretecms-community-store/community_store#647]
Hello,

I am getting a recurring log error from Community Store (2.3.4): `Exception Occurred: /...home-dir.../concrete/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:294 The identifier oID is missing for a query of Concrete\Package\CommunityStore\Src\CommunityStore\Order\Order (0)`

Any idea what this is, and is it causing orders to fail?

**Comment by Mesuva** [comment]
There's not much in that error log to be able to track down a cause.
I've found the same error in my development install's logs, but only once from a week or so ago - and that might have been caused by normal development. I have put lots of test orders through without issue with this install.

What payment gateway are you using?

**Comment by craigmarcussen** [comment]
I am using PayPal.

For the most part, orders have been going into the CS system flawlessly, and my client really appreciates the richness of the Dashboard, especially the ability to track the progress of the order.

**Comment by Mesuva** [comment]
Is your client using their Paypal account for purposes other than integration with CS?  (buttons, other websites, etc)

I'm just wondering if some Paypal callback are happening and that's where the error is popping up.

**Comment by craigmarcussen** [comment]
I can check, but I don't think so. I will look into that though.

There was a stretch in December where 3 sales were made, but they were not logged into the CS Dashboard. The invoice number were skipped in this case, so there is no record of the sales, but the transactions were completed in PayPal.

**Comment by Mesuva** [comment]
I've seen cases of Paypal having issues like that, then just working again.

I do have plans to write a new Paypal method, using Paypal Checkout, instead of the existing 'standard' integration.
