### ISSUE TITLE
Issue going from 2.3.1 -> 2.3.4

### ISSUE THREAD

**Issue by madesimplemedia** [concretecms-community-store/community_store#648]
Got an error about a missing DB column, so I manually added the column drDiscountSalePrices in the CommunityStoreDiscountRules table in PHPmyAdmin

I added it as an INT, is this correct?

**Comment by Mesuva** [comment]
A tinyint, yes.

An issue like that should be resolved by refreshing the doctrine entities, and then clearing the cache.
Did you try that?

**Comment by madesimplemedia** [comment]
Thanks.  I don't think I could access the site at all, but I will double check that in future
