### ISSUE TITLE
Ability to hide some product variants

### ISSUE THREAD

**Issue by JeRoNZ** [concretecms-community-store/community_store#651]
I have a scenario where a product has 8 sizes and 5 colours, which leads to 40 different variations. However, some variations do not actually exist, and in the case that I have before me, there are in fact only 28 saleable variants.

While a possible solution here is to leave those 12 as sold out, it's confusing for the end user and the administrator.

I was wondering if it's possible to add a check box to each variation that enables/disables the variant such that it does not appear as an option to the end user, and when it admin, it appears as a collapsed entry, i.e. it appears on a single line with the ability to expand on mouse click?

Is this something that might be useful in the core?

**Comment by Mesuva** [comment]
When you say ' does not appear as an option to the end user', what does that actually look like in terms of the interface?

When you've got multiple drop downs, and a variation is a combination of those drop downs, how would they then behave to not show the particular combination?  Or is it just the labelling that is the issue?

It does sound useful, but at the same time I often see these kinds of problems with variations and then suggest to split them to two products, or to have one drop down with all the options  But that also might not be logical for some types of product.

**Comment by JeRoNZ** [comment]
What it looks like depends on what options are currently selected.
For example, with nothing selected, both colour and size are shown.
If colour is selected, then only the sizes that are available in that colour are in the size select list. 
similarly, if size is chosen first, any colours not available in that size are not visible in the colour select list.

Reflecting on this a while, an easier alternative would be to have "Not Available" or similar flash up instead of "Out of Stock" so that the user isn't tempted to try to back order something that doesn't exist.
