### ISSUE TITLE
static calls to Filesystem::exists fail

### ISSUE THREAD

**Issue by danklassen** [concretecms-community-store/community_store#660]
This is likely a php8 issue, but calls to Filesystem::exists fail as it is not a static method.

Since the static method ends up just calling the php native function (https://github.com/illuminate/filesystem/blob/master/Filesystem.php#L26) is it reasonable to replace the calls with the php built in function?

(incoming PR with the relevant changes)

**Comment by Mesuva** [comment]
Yep this makes sense to me, as it looks like the exists function simply doesn't do anything of real value. Cheers.
