### ISSUE TITLE
A Question about Product Shipping (V2.4.6)

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#662]
In the Edit Product area, under Shipping there is a spot that says:
"Number Of Items"
0 is default, I assume this is number of items that can be shipped together?

**Comment by Mesuva** [comment]
Broadly speaking it's to indicate how a product should be treated in terms of counting 'items'.
An example might be some sort of bundle, where you've put two products together as one product to offer, but it really should be treated as two items.

The value is used in one case by discount rules, when you have minimums/maximums involved.
But it's not really used anywhere else. 

It probably should be being referred to by the built-in shipping methods, but it's not currently doing so. 

It's really just a reference field, or one that can be used by custom shipping methods if needed - by default it's really not used much.
