### ISSUE TITLE
Help getting product attribute names and values

### ISSUE THREAD

**Issue by rosie607** [concretecms-community-store/community_store#663]
this isn't a bug and I'm sorry if this is covered somewhere, I've searched and searched and can't seem to find the answer.

All I'm trying to do is list out all the selected attributes on a product.

In the documentation (https://concrete5-community-store.github.io/community_store/developers/attributes.html#product-attributes) it shows how to output an attribute but this seems to only output the value. I can't figure out how to get the ID, handle and name.

I can get the handle and name if I have the ID but I don't know how to get the ID.

This is what I've got working so far:

`

	//Returns a SPECIFIC attribute VALUE
	echo $product->getAttribute('lemon_peel') . '<br /><br />';
		
	// Returns a list of attribute VALUES for current product
	$productAtts = $product->getAttributes();
	foreach($productAtts as $productAtt) {
	  echo  $productAtt . '<br />';
	}
	
	// Returns list of ALL product attribute IDs
	$attrList = ProductKey::getList();
	foreach ($attrList as $ak) {
	        
	        echo $ak;
			$attributeKey = ProductKey::getByID($ak);
			
			$attributHandle = $attributeKey->getAttributeKeyHandle();
			echo $attributHandle;
			$attributeName = $attributeKey->getAttributeKeyName();
			echo $attributeName;
	
			echo  '<br />';
	}

`

**Comment by Mesuva** [comment]
When you've got $attributeKey, what happens when you just call  `getAttributeKeyID()` on it?
It _should_ work exactly the same as if it was a page attribute.. so if you can find an example of what you want to do with attributes in terms of pages, it should translate across.

Can I ask, why do actually need the ID?

**Comment by rosie607** [comment]
@Mesuva Sorry I might not have been clear with what I was struggling with. 
When I get a list of ALL available attributes I can get the ID from the attribute key. 
However when I use the following (just a list of attributes of the current product) I don't know how to get the rest of the attribute date (ID, Name, Handle). 
$product->getAttributes() and $product->getAttribute() only returns the value.

`$productAtts = $product->getAttributes();
foreach($productAtts as $productAtt) {
  echo  $productAtt . '<br />';
}`

**Comment by Mesuva** [comment]
```
$productAtts = $product->getAttributes(); 

foreach($productAtts as $productAtt) { 
    echo $productAtt;  // if echo is called directly on a product attribute, it outputs the display value.

    // but it's not a string, it's object you can call functions on still
    $ak = $productAtt->getAttributeKey();
    if ($ak && is_object($ak)) {
        echo $ak->getAttributeKeyHandle();
        echo $ak->getAttributeKeyDisplayName();
   }

}
```

**Comment by rosie607** [comment]
@Mesuva Thank you! 

This was the bit I was missing 
`$ak = $productAtt->getAttributeKey();`
