### ISSUE TITLE
Product List Block Page Selector

### ISSUE THREAD

**Issue by pvernaglia** [concretecms-community-store/community_store#667]
HI, Using Community Store 2.4.6 and have tried with Concrete 9.0.2 and 9.1RC3, when adding or editing the Product List Block changing List Products to one of the specific page options the page selector  does not display.

**Comment by pvernaglia** [comment]
Yes, getting Javascript error

jQuery.Deferred exception: $(...).select2 is not a function @https://dev.thehub.net/index.php?cID=1 line 2 > injectedScript:38:29
e@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:30038
Deferred/then/l/</t<@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:30340
setTimeout handler*Deferred/then/l/<@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:30549
c@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:28327
add@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:28605
Deferred/then/<@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:30645
Deferred@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:31058
then@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:30574
S.fn.ready@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:31864
@https://dev.thehub.net/index.php?cID=1 line 2 > injectedScript:2:17
b@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:866
He@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:48373
append@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:49724
html/<@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:50816
$@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:32425
html@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:50494
success@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:73:4886
c@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:28327
fireWith@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:29072
l@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:79901
send/o/<@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:82355
EventHandlerNonNull*send@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:82541
ajax@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:78291
$.fn.dialog.open@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:73:4727
addToDragArea@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:319:198066
pepStop@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:319:197348
stop@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:76373
r.prototype.handleStop@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:42569
r.prototype.subscribe/this.onStopEvents@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:38213
dispatch@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:43064
add/v.handle@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:41048
EventListener.handleEvent*add@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:41515
Ee/<@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:40109
each@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:3003
each@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:1481
Ee@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:40085
on@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:46578
r.prototype.subscribe@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:38243
r.prototype.init@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:37837
r@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:37586
[e.fn.pep/](chrome://devtools/content/webconsole/e.fn.pep/)<@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:54765
each@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:3003
each@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:1481
e.fn.pep@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:54711
init@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:76648
Concrete.Block@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:75423
scanBlocks/<@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:68642
each@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:3003
each@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:1481
scanBlocks@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:68430
scanBlocks/<@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:63123
each@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:3003
each@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:1481
scanBlocks@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:63024
init@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:62615
Concrete.EditMode@https://dev.thehub.net/concrete/js/cms.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:284:55198
@https://dev.thehub.net/index.php?cID=1:3128:28
e@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:30038
Deferred/then/l/</t<@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:30340
setTimeout handler*Deferred/then/l/<@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:30549
c@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:28327
fireWith@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:29072
fire@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:29108
c@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:28327
fireWith@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:29072
ready@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:32045
B@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:31824
EventListener.handleEvent*@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:32193
@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:220
@https://dev.thehub.net/concrete/js/jquery.js?ccm_nocache=55cde574af4b770a0d84d3b719dce4c690d76a03:2:225
 undefined

**Comment by Mesuva** [comment]
On v9, when the block loads its editing, it should be loading a copy of select2 from a vendor folder within Community Store itself.  (select2 was in v8, but not in v9, so it bundles a copy)
It should be loading it with a link like:
`<script type="text/javascript" src="/packages/community_store/vendor/select2/select2/select2.js?ccm_nocache=8b26e373aef0452ed71139e8151e26dafecff6bb&amp;ts=1651780421685"></script>`
Can you see that file in your Community Store package, and can you see it loading?

If it's something I can log into publicly, feel free to send an email to ryan@mesuva.co.uk with some details and I'll take a look at what is happening.

**Comment by pvernaglia** [comment]
I was missing vendor files, thanks for the help
