### ISSUE TITLE
PHP8: Undeclared variable breaks site if community utility links are placed

### ISSUE THREAD

**Issue by cahueya** [concretecms-community-store/community_store#668]
I just set a store live and when switching to PHP8.0 (and 8.1), die site breaks with PHP Exception because of the $shoppingDisabled variable in the utility links view.php

It has gone from notice to warning by the step to 8.0
[https://www.php.net/manual/en/migration80.incompatible.php](https://www.php.net/manual/en/migration80.incompatible.php).

**Comment by Mesuva** [comment]
The whole package has needed some cleanup for PHP8.

I've done a lots of this here, https://github.com/concrete5-community-store/community_store/commit/5cec6bf5664b7b5028d7771ae588b29d2d513884

But I expect there will be more things to fix
