### ISSUE TITLE
Need help for the display

### ISSUE THREAD

**Issue by Charles205050** [concretecms-community-store/community_store#670]
hi everyone, 
I have a project to do with an e-commerce site and so I used community store to do it, but I have two problems, 
my sales site does not need prices so how can I completely remove the display of prices of products? And the basket validation form is also not suitable for what is asking me, how can I change the fields of the fomrular? 

Thank you in advance, any help can be very helpful

**Comment by Mesuva** [comment]
Hiding pricing isn't too tricky, it's just about creating some custom templates where the price simply isn't output.
It starts to get a bit fiddly though in terms of the checkout and order receipts, as if you want to do ordering without showing pricing, you'd need to override those items. All doable, just might be quite a few places to adjust.

With the basket validation, what in particular do you need to change?

**Comment by Charles205050** [comment]
Thank you for your answer, how and where can I create a custom template? 

I would like to change the fields of the form for example I do not need to recover the customer’s phone or its location so I must delete these fields of the form . Thanks
