### ISSUE TITLE
Vendor folder not being installed

### ISSUE THREAD

**Issue by craigmarcussen** [concretecms-community-store/community_store#678]
Hello,

I installed the most recent version of CS into my Concrete 9.1.1 site, and noticed it was throwing **select2** JS errors when in edit mode. Any page with a CS block, and all Product editing pages in the Store section of the Dashboard were throwing the error. It turned out to be a missing **Vendor** folder in the CS package... easily fixed by grabbing the folder from a previous release of CS.

Not sure why this happened... I went through the usual update process using the Extend Concrete procedure. It has never been an issue in the past.

Craig

**Comment by Mesuva** [comment]
That's odd, when I download the latest release and unzip it, I'm seeing the vendor folder with a select2 folder in it.
What folder is missing?

**Comment by craigmarcussen** [comment]
No, from here:
https://github.com/concrete5-community-store/community_store

I used the CODE download button.

**Comment by Mesuva** [comment]
Yep, that's not the right place - always grab a release zip, from the Releases area on the right hand side of the main repo page.

That code download button is only ever going to download the files in git, and the vendor folder isn't ever pushed up to it.
The releases on the hand are packaged up and ready for use with the right folders included (and removed).
This is the same approach as Concrete itself, where you download an official release, not the master branch (which won't work without further commands to set it up).

Also, release zips are meant to be more predicable, as I put them out when there's no outstanding bugs/complaints, whereas the master branch can have at any point work-in-progress.  (in reality it rarely does, but the point still stands).
