### ISSUE TITLE
Call to a member function getPackageHandle() on null

### ISSUE THREAD

**Issue by aschottky** [concretecms-community-store/community_store#683]
After installing Community Store v.2.4.7.2 in ConcreteCMS 9.1.1 (brand new install) I get the following error when trying to access settings page:

Call to a member function getPackageHandle() on null

It seems the following call fails:

$pkg = $app->make('Concrete\Core\Package\PackageService')->getByID($this->pkgID);

**Comment by Mesuva** [comment]
Can you post a screenshot of the full debug?

**Comment by aschottky** [comment]
![Screen Shot 2022-08-09 at 08 50 37](https://user-images.githubusercontent.com/56620805/183699363-cc81d05d-dbf2-4abf-b322-b6d4f6b14439.jpg)

**Comment by aschottky** [comment]
It may have happened after installing stripe checkout but I did not visit settings page before installing stripe checkout method

**Comment by aschottky** [comment]
Stripe Checkout package is v.1.0.2

**Comment by Mesuva** [comment]
I was going to say it looks like something to do with a potentially broken payment method install.
Did Stripe Checkout install cleanly, and is it still sitting in the packages folder?
Can you see it registered in the CommunityStorePaymentMethods database table?

**Comment by aschottky** [comment]
I think you are correct - I will triple check and let you know. Thank you so much for your super quick responses!

**Comment by aschottky** [comment]
Ok. I removed everything and tried installing again and am getting this now:
![Screen Shot 2022-08-09 at 10 29 43](https://user-images.githubusercontent.com/56620805/183720165-c1462fcc-e8d4-4b45-a845-cf4d484b3f7a.jpg)

**Comment by aschottky** [comment]
The above error occured through install. The package looks installed but Product page in dashboard throws an error. Something wrong with attributes I assume

**Comment by aschottky** [comment]
PHP version wrong? This is concrete 9.0.2 and PHP 7.3.33

**Comment by Mesuva** [comment]
This is one of those recurring bugs that seems to pop up and then disappear. Sometime it's triggered by broken package installs. Sometimes it comes down to having other add-ons installed that do _things_ in the start of Concrete, and it breaks the way the Entities are loaded. There's not be a solution as such, as nearly everyone has reported this has also reported it going away.  I have tracked it down to the internals of Doctrine, it's not exclusively a CS bug as such.

Shouldn't be a PHP issue though, although I'd recommend you run a Concrete 9 site on 7.4
You also look a bit behind on your Concrete version, might be worth updating that. (you originally said 9.1.1, perhaps you meant that)

I'd try, removing both add-ons, clearing the cache and turning the cache off. Also try refreshing your database entities via /dashboard/system/environment/entities
then try to install CS again and see what happens.
