### ISSUE TITLE
Return a Response Object ff the request was made with Ajax

### ISSUE THREAD

**Issue by JeRoNZ** [concretecms-community-store/community_store#685]
I'm developing a payment method that is similar to the Stripe Checkout payment method, in that it loads an external JS file and submits the order using Ajax and doesn't actually use the html page that is returned.  See:
 
https://github.com/concrete5-community-store/community_store_stripe_checkout/blob/d5a7b70b01bcfd8f6e3a86b4f144ec33a774c500/elements/community_store_stripe_checkout/checkout_form.php#L28

I believe it would be a bit neater to return a Response object at this point:

https://github.com/concrete5-community-store/community_store/blob/515621c525e3648f4756bc182783334e1b293455/controllers/single_page/checkout.php#L339

If the request was made with AJAX, rather than carrying on and rendering the checkout page.

Adding in: 
```
		$ajax = $this->app->make('helper/ajax');
		if ($ajax->isAjaxRequest($this->request)){
			return new JsonResponse(['OK'=>1]);
		}
```
Seems to do the job nicely.

**Comment by Mesuva** [comment]
I've added this in, and is in https://github.com/concretecms-community-store/community_store/releases/tag/v2.4.7.6
(if you could test it, that would be great!)

**Comment by JeRoNZ** [comment]
Awesome. Looks fine to me. I ran a transaction through and it was remarkably unremarkable.

**Comment by Mesuva** [comment]
Love it - cheers for testing
