### ISSUE TITLE
Checkout page errors PHP 8.0.23

### ISSUE THREAD

**Issue by katalysis** [concretecms-community-store/community_store#687]
We're seeing undefined variable errors on the checkout page running PHP 8.0.23 for $activeShippingLabel and $shippingTotal.

**Comment by Mesuva** [comment]
This is with the latest release?

**Comment by katalysis** [comment]
Yes, 2.4.7.4

**Comment by Mesuva** [comment]
I must have missed testing shipping in PHP8, apologies.

Here's some fixes: https://github.com/concretecms-community-store/community_store/commit/f75137e1b343fd363453b3c27ad3e752a2f51f06

Let me know if you spot anything else, and once we're happy I'll put together a new release.
