### ISSUE TITLE
PHP 8.1 errors

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#688]
Undefined array key "switching_type"
I removed all the customizing I did, so it shouldn't be something I did.
https://www.mytinytown.com/liquid-level-controls
Switching System is where switching type would be.

Screen shot was with php 7.4
![Screen](https://user-images.githubusercontent.com/28864099/192869159-9a8acffc-02c9-46f7-828b-349de5007e50.png)

This is my live site, still running php 7.4
https://www.mdius.com/liquid-level-controls

**Comment by Mesuva** [comment]
I'm not entirely certain why this would be breaking, but you could try changing line 277 of packages/community_store/blocks/community_product_filter/controller.php
to be three lines:

```
if (isset($attributemapping[$handle][$item])) {
    ++$attributemapping[$handle][$item];
}
```

**Comment by mdius** [comment]
This removes the error, but shows empty filters.
Did I possibly mess up my attributes?
Are () ok in them?
![Attributes-top](https://user-images.githubusercontent.com/28864099/193029395-f230242d-3888-45f1-908a-f8a35d643dc0.png)
![Attributes-bottom](https://user-images.githubusercontent.com/28864099/193029416-9ab5cd1f-cbeb-494b-abb8-001940e5d662.png)

**Comment by Mesuva** [comment]
I don't think it matters, but it's been a while since I've looked at this code.

I used to have access to your dev site's cPanel - would you be able to send me an email with fresh credentials?   
I can then do a little debugging and get to the bottom of this.

**Comment by mdius** [comment]
The ( ) are ok with php7, so I assume that's not the issue.
I will send the credentials right now.

**Comment by Mesuva** [comment]
I've made some fixes for this, and you should see them on your test site now.
Those fixes are in: https://github.com/concretecms-community-store/community_store/releases/tag/v2.4.7.5

**Comment by mdius** [comment]
I may have found another issue or 2.
https://www.mytinytown.com/index.php/dashboard/store/discounts/addcodes/11
`
Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $successcount
`
`
/packages/community_store/controllers/single_page/dashboard/store/discounts.php
 
                foreach ($codes as $code) {
                    $code = trim($code);
 
                    if ($code) {
                        if (!DiscountCode::add($discountRule, $code)) {
                            $failed[] = $code;
                        } else {
                            ++$successcount;
                        }
                    }
                }
            }
        }
 
        if (!empty($failed)) {
            Session::set('communitystore.failedcodes', $failed);
        }
 
        $this->flash('success', $successcount . ' ' . (1 == $successcount ? t('Code Added') : t('Codes Added')));   <- Error line 197
 
        return Redirect::to('/dashboard/store/discounts/codes/' . $drID);
    }
 
    public function save()
    {
        if ($this->request->request->all() && $this->token->validate('community_store')) {
            $data = $this->request->request->all();
 
            if ($data['drID']) {
`

**Comment by mdius** [comment]
https://www.mytinytown.com/index.php/dashboard/store/discounts/add

`
Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $discountRule
`
`
packages/community_store/single_pages/dashboard/store/discounts.php
 
<?php if (in_array($controller->getAction(), $addViews)){ ?>
 
    <?php if ($controller->getAction() == 'edit') { ?>
        <div class="ccm-dashboard-header-buttons">
            <form method="post" id="deleterule" action="<?= Url::to('/dashboard/store/discounts/delete/')?>">
                <?= $token->output('community_store'); ?>
                <input type="hidden" name="drID" value="<?= $discountRule->getID(); ?>" />
                <button class="btn btn-danger" ><?= t('Delete'); ?></button>
            </form>
        </div>
    <?php } ?>
 
 
    <form method="post" action="<?= $this->action('save')?>" id="discount-add">
        <?= $token->output('community_store'); ?>
 
    <div class="ccm-pane-body">
 
        <?php if(!is_object($discountRule)){                               <- Error Line 264
            $discountRule = new DiscountRule(); //does nothing other than shutup errors.
            $discountRule->setTrigger('auto');
            $discountRule->setDeductType('percentage');
        }
        ?>
 
        <input type="hidden" name="drID" value="<?= $discountRule->getID()?>"/>
 
        <div class="form-group">
            <?= $form->label('drName', t('Name'))?>
`

**Comment by mdius** [comment]
Then on my fresh install, it seems if you do not have any Product Groups added adding a discount rule causes an error.
http://concrete.mytinytown.com/index.php/dashboard/store/discounts/add
`
Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $productgroups
`
`
/home/tinytown/public_html/subs/concrete.mytinytown.com/packages/community_store/controllers/single_page/dashboard/store/discounts.php

        $this->set('pageTitle', t('Discount Rules'));
 
        $headerSearch = $this->getHeaderSearch();
        $this->set('headerSearch', $headerSearch);
    }
 
    public function add()
    {
        $this->requireAsset('selectize');
        $this->set('pageTitle', t('Add Discount Rule'));
 
        $grouplist = StoreGroupList::getGroupList();
        $this->set("grouplist", $grouplist);
        foreach ($grouplist as $productgroup) {
            $productgroups[$productgroup->getGroupID()] = $productgroup->getGroupName();
        }
        $this->set("productgroups", $productgroups);   <-   Error Line 56
 
        $gl = new GroupList();
        $gl->setItemsPerPage(1000);
        $gl->filterByAssignable();
        $usergroups = $gl->getResults();
`


I hope I'm not being annoying with these. If I am not, would you like me to test things a little more and see what I find?

**Comment by Mesuva** [comment]
Not in the slightest, these reports are great - I've not had a huge chance to review everything for PHP8, so these are a great help.

**Comment by Mesuva** [comment]
I've fixed these things in https://github.com/concretecms-community-store/community_store/releases/tag/v2.4.7.6
