### ISSUE TITLE
PHP 8.1 error

### ISSUE THREAD

**Issue by SB1955** [concretecms-community-store/community_store#689]
Fresh local install.
M1 Mac
Mamp: V6.6
CMS: V9.1.2
Store: V2.4.7.4
PHP: 8.1
Most things seem to work so far except for trying to add a shipping method.
Error: ‘Undefined variable $sm’  on line 100 in store/single_pages/dashboard/store/settings/shipping.php. 
Line 100: <?php isset($smt) ? $smt->renderDashboardForm($sm) : false; ?>

**Comment by Mesuva** [comment]
I made this fixes yesterday actually - https://github.com/concretecms-community-store/community_store/commit/f75137e1b343fd363453b3c27ad3e752a2f51f06

There's not in a release yet, but I can put one together this week.  Really just wanted to confirm there weren't other issues from these fixes first.

**Comment by Mesuva** [comment]
These fixes should be in this release:
https://github.com/concretecms-community-store/community_store/releases/tag/v2.4.7.5
