### ISSUE TITLE
PHP 8.1.10 Error Fresh Install

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#690]
I set up a test site to do everything with a completely new install. Everything about the Community Store (v2.4.7.4) is 100% fresh and unedited.
http://concrete.mytinytown.com/
When trying to install I get:
Whoops \ Exception \ ErrorException (E_WARNING)
Undefined array key "taxClassRates"
/subs/concrete.mytinytown.com/packages/community_store/src/CommunityStore/Tax/TaxClass.php

``` 
public static function add($data)
    {
        $locked = 0;
        if ($data['taxClassLocked']) {
            $locked = $data['taxClassLocked'];
        }
        $tc = new self();
        $th = Application::getFacadeApplication()->make("helper/text");
        $tc->setTaxClassHandle($th->handle($data['taxClassName']));
        $tc->setTaxClassName($data['taxClassName']);
        $tc->setTaxClassRates($data['taxClassRates']);    <- This line 162 shows the error.
        $tc->setTaxClassLock($locked);
        $tc->save();
 
        return $tc;
    }
```

If you liked to further look at this, you have my info. It is under tinytown.
I will leave it uninstalled.

**Comment by theblobinc** [comment]
I'm having the same issue on a freshly deployed instance of concretecms using the latest version of Community Store - 2.4.7.4

**Comment by Mesuva** [comment]
I've (hopefully) fixed these issues with some bugfixing, and this new release here:
https://github.com/concretecms-community-store/community_store/releases/tag/v2.4.7.5

**Comment by theblobinc** [comment]
My employer suggested I revert the instances PHP version back to 7.4 which seems to have resolved my immediate issues,
in the future I will definitely be sure to test out the new release.
(we end up having to doing that with a lot of the newer concretecms instances we build and host since updating to PHP 8)
