### ISSUE TITLE
New Release controller.php

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#691]
It looks like you forgot the change the controller to 2.4.7.6 from 2.4.7.5. But I'm testing it right now and I'll let you know if I run in to any other issues.
Do you think the PayPal and Authorize payments will work? As well Easypost? Of course, I'll test those too. If I find issues, I'll post them in the proper place.

**Comment by mdius** [comment]
On my fresh install test site, /dashboard/store/reports/products gave an error. There are no sales, it is working on my backed up test site with sales.
Whoops \ Exception \ ErrorException (E_WARNING)
Undefined array key "oDate"

/packages/community_store/src/CommunityStore/Order/OrderList.php
`

 
    public static function getDateOfFirstOrder()
    {
        $app = Application::getFacadeApplication();
        $db = $app->make('database')->connection();
        $date = $db->GetRow("SELECT * FROM CommunityStoreOrders ORDER BY oDate ASC LIMIT 1");
 
        return $date['oDate'];    <-  Line Error 273
    }
 
    public function getOrderItems()
    {
        $orders = $this->getResults();
        $orderItems = [];
        $app = Application::getFacadeApplication();
        $db = $app->make('database')->connection();
        foreach ($orders as $order) {
`

**Comment by mdius** [comment]
Well about my first comment, it looks like the zip file is version 2.4.7.5
The source files seem to be correct. 
Going to download the source and see if that makes any differences.

**Comment by Mesuva** [comment]
I was trying out a new way to zip up the package - that obviously didn't work right!

I've created a new version here: https://github.com/concretecms-community-store/community_store/releases/tag/v2.4.7.7
That includes a fix for the report bug.

In terms of related add-ons, they _might_ work for PHP8 as is, but I've simply not had a chance to test them. If you do find issues, yes, report away.

**Comment by mdius** [comment]
I think I found another bug. It even does the same on my fresh install.
https://www.mytinytown.com/index.php/dashboard/store/products/edit/1588
When the stock level unlimited is not checked :
Whoops \ Exception \ ErrorException (E_WARNING)
Undefined array key "pQtyUnlim"

/packages/community_store/src/CommunityStore/Product/Product.php
`

       if ($data['pSaleEnd_dt']) {
            $product->setSaleEnd(new \DateTime($data['pSaleEnd_dt'] . ' ' . $data['pSaleEnd_h'] . ':' . $data['pSaleEnd_m']  . (isset($data['pSaleEnd_a']) ? $data['pSaleEnd_a'] : '') ));
        }else {
            $product->setSaleEnd(null);
        }
 
        $product->setIsFeatured($data['pFeatured']);
        $product->setQty(isset($data['pQty']) ? $data['pQty'] : 0);
        $product->setIsUnlimited($data['pQtyUnlim']);     <- Line Error 1085
        $product->setAllowBackOrder($data['pBackOrder']);
        $product->setNoQty($data['pNoQty']);
        $product->setTaxClass($data['pTaxClass']);
`

**Comment by mdius** [comment]
Also, now today, I can not add a product on either the test or fresh sites.
I have not updated or changed anything on the server, it is still PHP 8.1.10. It works fine if I change it back to PHP 7.4

Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $pgroups

/packages/community_store/single_pages/dashboard/store/products.php
`

                        <select multiple="multiple" name="pProductGroups[]" class="existing-select2 select2-select" style="width: 100%"
                                placeholder="<?= (empty($productgroups) ? t('No Product Groups Available') : t('Select Product Groups')); ?>">
                            <?php
                            if (!empty($productgroups)) {
                                if (!is_array($pgroups)) {      <- Line Error 733
                                    $pgroups = [];
                                }
                                foreach ($productgroups as $pgkey => $pglabel) { ?>
                                    <option value="<?= $pgkey; ?>" <?= (in_array($pgkey, $pgroups) ? 'selected="selected"' : ''); ?>>  <?= $pglabel; ?></option>
                                <?php }
                            } ?>
`

**Comment by mdius** [comment]
I have 1 more issue.
On my test server. It seems to be related to the attributes. I won't through all my attributes and re-saved them to see if any of them errored and none did. But if this this is a core concrete issue I'll take it to the concrete forum.

https://www.mytinytown.com/index.php/dashboard/store/products/edit/1588

Whoops \ Exception \ ErrorException (E_WARNING)
Trying to access array offset on value of type null

/updates/concrete-cms-9.1.2/concrete/attributes/select/controller.php
`

        if ($akSelectAllowMultipleValues && !$akSelectAllowOtherValues) {
            // checkbox list.  No new options.
            $options = [];
            if (is_array($data['atSelectOptionValue'])) {     <-  Line Error 260
                foreach ($data['atSelectOptionValue'] as $optionID) {
                    $option = $this->getOptionByID($optionID);
                    if (is_object($option)) {
                        $options[] = $option;
                    }
                }
            }
`

**Comment by Mesuva** [comment]
Thanks for these reports, I've pushed up a few more fixes.
I'm not put together a new release yet, I might do a little more testing on my end before I do that.

With the last one, about the attributes, I do suspect that's a core issue, but I will look into it too.

**Comment by mdius** [comment]
I did add a couple attributes to my fresh install and they seemed to have worked. But I have a lot more attributes on my live site.

**Comment by mdius** [comment]
Filter Error on my fresh install. I'm going to try to fix the errors to see if I can test things further.
http://concrete.mytinytown.com/liquid-level-controls

When trying to add a new filter in the model window there is an error.
Undefined variable $groupMatchAny

/packages/community_store/blocks/community_product_filter/edit.php(74): Whoops\Exception\ErrorException->null


Same for adding a Product List.
Undefined variable $filterManufacturer

/packages/community_store/blocks/community_product_list/form.php(110): Whoops\Exception\ErrorException->null


Utility Links Block addition worked.
Product Block addition worked.

**Comment by mdius** [comment]
On fresh install
http://concrete.mytinytown.com/checkout
Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $codeerror

/packages/community_store/controllers/single_page/checkout.php

                if ($this->request->request->get('code')) {
                    $codesuccess = DiscountCode::storeCartCode($this->request->request->get('code'));
                    $codeerror = !$codesuccess;
                } else {
                    DiscountCode::clearCartCode();
                }
            }
 
            $this->set('codeerror', $codeerror);   <--  Line Error 50
            $this->set('codesuccess', $codesuccess);

**Comment by Mesuva** [comment]
I've pushed more fixes to address the things you've raised above (https://github.com/concretecms-community-store/community_store/commit/85a62b9115c741369b10c10da82b7dfcada0aa8e)

Thanks again, these prompts are very useful
