### ISSUE TITLE
Request for plugin

### ISSUE THREAD

**Issue by baxterdmutt** [concretecms-community-store/community_store#694]
Has anyone considered adding a payment addon for Square payments. They are a pretty big payment gateway. If I was a bit better add coding I’d give it a try but sadly I’m not.

**Comment by Mesuva** [comment]
There is this one:
https://github.com/Babinsky/community_store_square

It's a bit old now, and I think the release might need updating from the master/main branch, but the last that I heard it's still working. I think it just might be using Square's older integration. I've done some work with Square, but just not with Community Store.  

I agree it's a pretty big gateway, the challenge is that payment gateway add-ons can be a lot of work to develop and test, so unless there's a business case to build one, it's not something I'm likely to just do for the sake of it.

**Comment by baxterdmutt** [comment]
Thanks for that. I see on squares developers site that they have php sdk examples, and while I understand the code, I doubt I could implement it.  I’ll look at the one you linked for me.

**Comment by baxterdmutt** [comment]
It's really too bad someone isn't willing to help out on this. I have always found that to be a major shortcoming with ConcreteCMS. It's so easy to use compared to every other CMS, but the plugins just aren't there. Maybe someone with a little time on their hands will jump in here and try throwing something together. I can only hope.

**Comment by Mesuva** [comment]
@baxterdmutt I'd say my main question at this point is, are you needing this add-on for a:
- commercial project
- personal project
- non-profit or charity project?

**Comment by baxterdmutt** [comment]
@Mesuva so you know this no longer works. I did read on the square site that they no longer accept from the old api
I have a charity (service dogs for veterans and first responders) that I am a director with. I wanted to use square in the kitshop. I did some reading and I’m gonna try taking a stab at this. If I can’t then maybe I’ll come back for help.

**Comment by dbuonomo** [comment]
@baxterdmutt, I don't see a way to contact you privately via GitHub. I sent you a private message via messages on the Concrete CMS website.

**Comment by Mesuva** [comment]
@baxterdmutt That's fantastic, I'll look to update links wherever I find them to this replacement method
