### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#696]
Using ConcreteCMS 9.1.2
PHP 8.1.11
It goes away if I switch back to PHP 7.3, it happens when I Update a product.
It only happens on the both sites that have old products, it does not happen on the fresh install. I did post this in the Concrete CMS site too.

Error "/updates/concrete-cms-9.1.2/concrete/attributes/select/controller.php"
```
        if ($akSelectAllowMultipleValues && !$akSelectAllowOtherValues) {
            // checkbox list.  No new options.
            $options = [];
            if (is_array($data['atSelectOptionValue'])) {             <- Error on this line (260)
                foreach ($data['atSelectOptionValue'] as $optionID) {
                    $option = $this->getOptionByID($optionID);
                    if (is_object($option)) {
                        $options[] = $option;
                    }
                }
            }
```
https://www.mytinytown.com/
If you want to test it.

**Comment by Mesuva** [comment]
From where this error message comes from, I do think this is a core issue, rather than one I can resolve through Community Store.

**Comment by mdius** [comment]
I am pretty sure I posted this before and you said the same thing. But I felt putting it here to see if anyone else is dealing with it as well.
But, it does seem to save all the changed data, except the attributes. I really wonder if there is something in my attributes that either php8.1 or Concrete 9 doesn't like.

**Comment by mdius** [comment]
So, I think I know what happened here. It is an issue that I caused when adding my attributes.
I tried to delete them all on my test site to see what happens and there were 4 that would not delete. Pretty certain those 4 I tampered with to save some time.
Lesson learned.

**Comment by mdius** [comment]
I must make a correction, it is a core issue.
If you use an attribute Option List and use the Select Option Allow multiple options... and you do not choose an option on your product page for that attribute, it throws the above error.

**Comment by Mesuva** [comment]
That makes perfect sense - when you don't check an input on an HTML that value is simply not sent, so atSelectOptionValue is not going to exist if there isn't at least one thing checked.

I've done a PR for this - was already a known bug.
https://github.com/concretecms/concretecms/pull/11051
