### ISSUE TITLE
2 different issues: Undefined variable $lastPaymentMethodHandle and Undefined array key "quantity"

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#699]
This is on my fresh install site and my full backup site.
ConcreteCMS 9.1.3
CS 
PHP 8.1.12

The first error
Undefined variable $lastPaymentMethodHandle
/packages/community_store/single_pages/checkout.php
```
$i = 1;
foreach ($enabledPaymentMethods as $pm) {
    if (!isset($lastPaymentMethodHandle) && $i == 1 || $lastPaymentMethodHandle == $pm->getHandle()) {   <-- Error line 465
        $props = ['data-payment-method-id' => $pm->getID(), 'checked' => 'checked'];
    } else {
        $props = ['data-payment-method-id' => $pm->getID()];
    }
```
I changed it to  `if (!isset($lastPaymentMethodHandle) && $i == 1 || isset($lastPaymentMethodHandle) && $lastPaymentMethodHandle == $pm->getHandle()) {` 
This seemed to clear it up.

2nd Issue
Undefined array key "quantity"'
/packages/community_store/single_pages/cart.php
```
    <?php if ($actiondata['quantity'] != $actiondata['added']) { ?>  <-- Error Line 33
        <p class="alert alert-warning"><?= t('Due to stock levels your quantity has been limited'); ?></p>
    <?php } ?>
<?php } ?>
```
This error happens when you are in you cart
http://concrete.mytinytown.com/cart
Then you delete an item. The item gets deleted, but the error happens.

**Comment by Mesuva** [comment]
Thanks again for these reports, very handy.
I've addressed both through this update: https://github.com/concretecms-community-store/community_store/commit/5277e14fde027fb415e22ff6782e6d9ba4741d1c
