### ISSUE TITLE
JSON error on add to cart

### ISSUE THREAD

**Issue by katalysis** [concretecms-community-store/community_store#704]
I'm getting a recurring error relating to jquery parsing json data in communityStore.js line 125 when adding to cart on a store with a trailing / set for the urls. The site has recently been upgraded to Version 9 and Community Store 2.4.7.8 but it feels like it may be related to previous issue: #387

The issue seems to be temporarily resolved by clearing the Concrete CMS cache everything then works until the issue returns later.

**Comment by Mesuva** [comment]
That's odd then that it temporarily resolves with a cache clear. Off the top of my head I can't think of a reason that would happen. 

I'm assuming this isn't a multilingual site?

**Comment by katalysis** [comment]
It may have been caused by having full page cache settings on regardless of blocks allowing.  We'll investigate further.
