### ISSUE TITLE
Undefined variable $product

### ISSUE THREAD

**Issue by nickratering** [concretecms-community-store/community_store#707]
With a fresh install, v 2.4.8.2, Concrete CMS 9.1.3, PHP 8.1, adding my first product:
Whoops\Exception\ErrorException Undefined variable $product
In /packages/community_store/controllers/single_page/dashboard/store/products.php r.466

**Comment by Mesuva** [comment]
This should be resolved in https://github.com/concretecms-community-store/community_store/releases/tag/v2.4.8.4
