### ISSUE TITLE
Adding a new product list filter - Undefined variable $groupMatchAny

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#709]
This happens on my fresh install and my test site. But when I try to add a new product filter I get the following error.
```
Undefined variable $groupMatchAny

/packages/community_store/blocks/community_product_filter/edit.php(92): Whoops\Exception\ErrorException->null
```
Putting the following just before that line seems to fix it.
```
<?php if (!isset($groupMatchAny)) {
    $groupMatchAny = '';
} ?>
```

Also, I get an error on my test site. It appears to be if you delete an attribute before removing it from your filter, it causes the following error. It does not cause the error if I switch it to PHP 7.4.
```
Undefined array key 103

/packages/community_store/blocks/community_product_filter/edit.php(182): Whoops\Exception\ErrorException->null
```
I have not found a way to fix this yet.

**Comment by Mesuva** [comment]
I believe this one has been fixed in the master branch
