### ISSUE TITLE
"Undefined array key "pvSKU""

### ISSUE THREAD

**Issue by baxterdmutt** [concretecms-community-store/community_store#713]
I'm getting this error when duplicating a product. The products duplicates and then when I make any (or no change at all) and click update product this error is thrown. I'm using concrete 9.1.2 and php 8.0.3.  Now, I thought concrete was a all set to use php 8 but if I switch back to php 7.4, this issue is resolved.

`Whoops\Exception\ErrorException thrown with message "Undefined array key "pvSKU""
Stacktrace:
#26 Whoops\Exception\ErrorException in /usr/local/share/concrete5/concrete-cms-9.1.2/packages/community_store/src/CommunityStore/Product/ProductVariation/ProductVariation.php:566
#25 Whoops\Run:handleError in /usr/local/share/concrete5/concrete-cms-9.1.2/packages/community_store/src/CommunityStore/Product/ProductVariation/ProductVariation.php:566
#24 Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductVariation\ProductVariation:addVariations in /usr/local/share/concrete5/concrete-cms-9.1.2/packages/community_store/controllers/single_page/dashboard/store/products.php:454
#23 Concrete\Package\CommunityStore\Controller\SinglePage\Dashboard\Store\Products:save in /usr/local/share/concrete5/concrete-cms-9.1.2/packages/community_store/controllers/single_page/dashboard/store/products.php:155
#22 Concrete\Package\CommunityStore\Controller\SinglePage\Dashboard\Store\Products:edit in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Controller/AbstractController.php:318
#21 call_user_func_array in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Controller/AbstractController.php:318
#20 Concrete\Core\Controller\AbstractController:runAction in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/ResponseFactory.php:188
#19 Concrete\Core\Http\ResponseFactory:controller in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/ResponseFactory.php:367
#18 Concrete\Core\Http\ResponseFactory:collection in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/DefaultDispatcher.php:132
#17 Concrete\Core\Http\DefaultDispatcher:handleDispatch in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/DefaultDispatcher.php:60
#16 Concrete\Core\Http\DefaultDispatcher:dispatch in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/DispatcherDelegate.php:39
#15 Concrete\Core\Http\Middleware\DispatcherDelegate:next in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/FrameOptionsMiddleware.php:39
#14 Concrete\Core\Http\Middleware\FrameOptionsMiddleware:process in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/MiddlewareDelegate.php:50
#13 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/StrictTransportSecurityMiddleware.php:36
#12 Concrete\Core\Http\Middleware\StrictTransportSecurityMiddleware:process in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/MiddlewareDelegate.php:50
#11 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/ContentSecurityPolicyMiddleware.php:36
#10 Concrete\Core\Http\Middleware\ContentSecurityPolicyMiddleware:process in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/MiddlewareDelegate.php:50
#9 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/CookieMiddleware.php:35
#8 Concrete\Core\Http\Middleware\CookieMiddleware:process in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/MiddlewareDelegate.php:50
#7 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/ApplicationMiddleware.php:29
#6 Concrete\Core\Http\Middleware\ApplicationMiddleware:process in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/MiddlewareDelegate.php:50
#5 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/Middleware/MiddlewareStack.php:86
#4 Concrete\Core\Http\Middleware\MiddlewareStack:process in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Http/DefaultServer.php:85
#3 Concrete\Core\Http\DefaultServer:handleRequest in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Foundation/Runtime/Run/DefaultRunner.php:125
#2 Concrete\Core\Foundation\Runtime\Run\DefaultRunner:run in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/src/Foundation/Runtime/DefaultRuntime.php:102
#1 Concrete\Core\Foundation\Runtime\DefaultRuntime:run in /usr/local/share/concrete5/concrete-cms-9.1.2/concrete/dispatcher.php:45
#0 require in /home/meliora/web/melioraservicedogs.com/public_html/index.php:2
`

**Comment by Mesuva** [comment]
I think PHP8 usage here has just uncovered a bug, one that was previously being hidden by more forgiving code.

See the fix here: https://github.com/concretecms-community-store/community_store/issues/713
(the second change is the main one)
