### ISSUE TITLE
Categorize under page

### ISSUE THREAD

**Issue by baxterdmutt** [concretecms-community-store/community_store#714]
I am unable to get this to work. I’ve created a page type “Product Categories” a product list block is in that page with product list set to “Categorize under current page”.  This new page type is place under “Products” in the site. When I go into a product - “Catagories and Groups” and choose the categories page I added. It shows chosen and after I click “update product” the selection goes blank and the new page does not show any products. If tried this a ton of different way and just can’t get it to work. I had a previous problem with php 8 so I’m no longer on php8. I’ve switched back to 7.4.  I’m using Concrete 9.1.2. Oh, and I’m using the most recent community store. Downloaded it this morning.

**Comment by Mesuva** [comment]
I just tried this on my local development copy and wasn't hitting this issue. 
Could it be something simple like not having the product active?

Feel free to include some screenshots, or you're welcome to email through some details for me to look at.

**Comment by baxterdmutt** [comment]
Ok, I’m not able to include the screenshots today,  but the products are active. I’ve tried in products that have variations as well as single products and the results are always the same. Could this be some strange privilege issue. Can you direct me to a log that I could look at?

**Comment by baxterdmutt** [comment]
And now I’m seeing another issue. If I’m editing the page I wish to use for the catagorize page, the drop-down list give 
** All **
Catagorize under page
Catagorize under page and child pages 
Catagorize under a specific page (this option causes an error because there is no option for me to enter a specified page.

**Comment by baxterdmutt** [comment]
Thanks for your help @Mesuva . Indeed the issue was that I installed from the "master" instead of the "latest release" 
I'm not sure how I missed it but I've got it working now. Thanks again
