### ISSUE TITLE
Editing product attributes

### ISSUE THREAD

**Issue by pvernaglia** [concretecms-community-store/community_store#715]
Hi, using community store 2.4.8.4 and Concrete 8.5.12 when we try to edit product text attributes the new content does not save, the page reloads with the original content, no error messages, other sections of the edit page save correctly.  Anyone else seeing this or have any suggestions?  thanks

**Comment by Mesuva** [comment]
Is it fixed by this: https://github.com/concretecms-community-store/community_store/commit/72e3f5a5e303b7dcbc2fa7def61f4b61fc7349a8  ?

**Comment by pvernaglia** [comment]
Yes,that fixes it, thank you
