### ISSUE TITLE
[PHP8] Undefined Array Key [drProductGroups]

### ISSUE THREAD

**Issue by katalysis** [concretecms-community-store/community_store#717]
When using a discount rule in PHP 8 and the latest 2.4.8.4 version, this returns an undefined array key error for [drProductGroups]

line 631 in packages/community_store/src/CommunityStore/Discount/DiscountRule.php

$dpg = trim($row['drProductGroups']);

changing to 

$dpg = trim(isset($row['drProductGroups']));

rectifies the issue.

**Comment by Mesuva** [comment]
Thanks for this. I actually believe that line of code was doing nothing, so I've simple removed it.
