### ISSUE TITLE
Community Store not working in Concrete 8.5.12

### ISSUE THREAD

**Issue by vvinci00** [concretecms-community-store/community_store#720]
Hello,

I'm using Community Store v. 2.4.8.5 in Concrete 8.5.12 and I'm having some issue:
- When click on "Add to Cart" button there's an "loading page spinner" but nothin happen.
- Cart and Checkout pages has not been created 
- Products page has not been created

Iv'e used the Store in Concrete 9 with no issue but, at now, is not possible to upgrade the current Concrete 8.5.12 for other add-on and theme compatibility reason.

what I've to do in order to let it work in current environment?

Thanks

**Comment by Mesuva** [comment]
That sounds like the install failed - did you see any error messages when you installed Community Store?

**Comment by vvinci00** [comment]
nope, no error

**Comment by vvinci00** [comment]
I've tried to remove and install it again and now appear an error during installation:

at `/app/packages/community_store/src/CommunityStore/Utilities/Installer.php:478`

`Call to a member function setAttribute() on null`

**Comment by Mesuva** [comment]
Thats handy, thank you.

I'm planning to do some work on Community Store in the next week, I'll test the install out under V8 then.

**Comment by vvinci00** [comment]
hi,
seems that I've installed the plugin in wrong timeline.
Installing firstly the theme and after the store it work fine.
