### ISSUE TITLE
Error on save if empty option list attribute

### ISSUE THREAD

**Issue by danread33** [concretecms-community-store/community_store#723]
There is an error on saving a product if an 'Option List' product attribute, that allows multiple options to be selected, does not have any values selected.

 
![Product edit attributes](https://user-images.githubusercontent.com/25725101/216380460-323aaa09-0879-4b44-a5a0-35bb1346bc13.png)
![error](https://user-images.githubusercontent.com/25725101/216380463-2f48e6c2-b1fe-4ba5-8e09-0b498239f034.png)
![Attribute setup](https://user-images.githubusercontent.com/25725101/216380466-bd05767b-2aa4-439b-a1ab-6d022c46f387.png)

**Comment by Mesuva** [comment]
I just tried this on V9 and the latest version of Community Store and couldn't get it to error.
What versions are you running of Concrete and CS?

**Comment by danread33** [comment]
I have Concrete 9.1.3 and the latest version of community cart. I wonder if it happens when there are multiple attributes? I have 6 attributes that are 'Option Lists' that allow multiple selections. I'll have a play with it some more to see if I can isolate it. Maybe something to do with product types. I'll try a few different things and let you know

**Comment by Mesuva** [comment]
Ah yep, it's to do with product types. Will look into this further

**Comment by Mesuva** [comment]
I believe this isn't to do with empty checkboxes, it's when you've got product types, and you save down and attributes aren't present.

Try this: https://github.com/concretecms-community-store/community_store/issues/723

**Comment by danread33** [comment]
That's fixed it. You're a star. Thanks for looking into this so quickly.
