### ISSUE TITLE
blocks/community_utility_links/form.php

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#724]
Line 32 is `<?= $form->checkbox('showGreeting', 1, isset($showSignIn) ? $showSignIn : 1); ?>` and should be `<?= $form->checkbox('showGreeting', 1, isset($showGreeting) ? $showGreeting : 1); ?>`

**Comment by Mesuva** [comment]
Thanks for this, nice spot - I've committed a fix
