### ISSUE TITLE
Option List

### ISSUE THREAD

**Issue by SB1955** [concretecms-community-store/community_store#742]
Option List will not remove. After updating product the list returns?

Store 2.4.85
CMS 9.1.3
PHP 8.1.15

**Comment by SB1955** [comment]
Sorry updated php file, still holds onto list?

**Comment by Mesuva** [comment]
Sorry, I was mixing this up with attribute lists. Yes, I can see how option lists can't be removed. Will investigate.

**Comment by Mesuva** [comment]
Try this fix here: https://github.com/concretecms-community-store/community_store/commit/53ea8932afce2ae423fa17ebbff746beb28fe59f

**Comment by SB1955** [comment]
Good man, thank you so much, fixed for me.
Q: BTW: Do u get much sleep?

**Comment by penbox-ad** [comment]
Same problem occured to me, I couldn't remove options. I resolved it to add Hidden Value after Option List, then I can can remove options and after saving options are empty.
