### ISSUE TITLE
Option List multi select (v9)

### ISSUE THREAD

**Issue by penbox-ad** [concretecms-community-store/community_store#744]
I have products (travel packages) with Option List to choose extra services.
As default I can list options list as drop-down or radio buttons but I can choose only one option. My need is to choose several options with price adjustment. 

How I can make this as multi selectable?

**Comment by Mesuva** [comment]
That sounds like you need to create more options, instead of trying to keep them in just one option list

**Comment by penbox-ad** [comment]
Of course! I'll do it that way, thanks Ryan.
