### ISSUE TITLE
select2 installed to js folder instead of vendor

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#745]
Is there any reason to install select2 as a composer package?

Why? For example, let's assume that we start with a composer-based Concrete project [like this](https://github.com/mlocati/concretecms-skeleton).

If we add `concrete5-community-store/community_store` as a composer dependency, the package will be installed in
```
/web/packages/community_store
```
(that is, under the `web` webroot), but its dependencies will be installed in
```
/vendor
```
(that is, outside the webroot).

But Community Stores assumes that the composer dependencies are installed under
```
/web/packages/community_store/vendor
```

The solution is simply to remove select2 from the composer dependencies, and install it exactly the same way we already install other npm packages.

**Comment by Mesuva** [comment]
I can't remember the reason for this. It may have been to do with packaging up releases.
