### ISSUE TITLE
Not available on packagist?

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#748]
We have a `composer.json` package that defines `concrete5-community-store/community_store` as the name of the Composer package.

Is there any reason why it's [not published on packagist](https://packagist.org/?query=concrete5-community-store%2Fcommunity_store)?

**Comment by Mesuva** [comment]
I think the reason has been I've simply not known how to publish it on packagist _and_ have it handle the npm install requirements.

**Comment by mlocati** [comment]
> _and_ have it handle the npm install requirements.

The npm assets [are copied outside the `node_modules`](https://github.com/concretecms-community-store/community_store/blob/v2.4.8.5/package.json#L18-L55) folder and added to the git repository, aren't they?
If so, people don't need to install the npm packages, isn't it?

**Comment by Mesuva** [comment]
That's a good point. 
I believe I was thinking that those resources hasn't been committed to git, but they obviously have been. So packagist should work.

**Comment by mlocati** [comment]
I've just noticed that in the .zip file attached to the [release page](https://github.com/concretecms-community-store/community_store/releases/tag/v2.5), we have a `components` directory: what's it useful for?
If it's required, what about adding to the git repository?

**Comment by Mesuva** [comment]
I actually don't know why that folder is there!
I included it as I included it in the last release.. but I'm not actually seeing why it's there... it must be as part of some build process, but it shouldn't be included in a release.

I might pull down the last release and issue a new one (with another fix I want to push anyway)

**Comment by mlocati** [comment]
> I actually don't know why that folder is there!

Maybe you have it in your local clone of the repository, but since it's listed in the `.gitignore` file you don't see it when you make commits.

**Comment by Mesuva** [comment]
Yes, I think my local copy goes back to 2016!

**Comment by Mesuva** [comment]
I've pushed up a new release, one that actually doesn't even include the vendor folder.
I'll see about getting it on packagist, as I think it'll be good to go up now.

**Comment by mlocati** [comment]
The vendor folder is needed only when people don't use composer to install a package (that is, people that manually download the zip archive and extract it in the packages folder).

When a package is installed via composer, the composer dependencies are ibsralled automatically by composer in the project vendor folder (which usually resides outside the web root, and that's much safer)

**Comment by mlocati** [comment]
> I've pushed up a new release, one that actually doesn't even include the vendor folder.

Whoops, now I understand: there's no composer dependencies! So, yep; the vendor folder is not needed

**Comment by mlocati** [comment]
What about renaming the package in the composer.json file from `concrete5-community-store/community_store` to `concretecms-community-store/community_store`?
