### ISSUE TITLE
Adding a new product list filter - Undefined variable $groupMatchAny

### ISSUE THREAD

**Issue by webpresso-ch** [concretecms-community-store/community_store#753]
After updating to the latest Community-Store version, I get the following error message when adding a new product filter Block:

```
Undefined variable $groupMatchAny
/packages/community_store/blocks/community_product_filter/edit.php(92):  Whoops\Exception\ErrorException->null
```
If I set `$this->set('groupMatchAny', '');` in  `/packages/community_store/blocks/community_product_filter/controller.php` in the add() function everything works as expected.

**Comment by Mesuva** [comment]
I believe this one has been fixed, it just hasn't made it's way into a release yet:
https://github.com/concretecms-community-store/community_store/commit/a0212f76bd87ed05c0aa2e39618680660509118f

I'm overdue for putting out a new release, will be looking at that soon

**Comment by webpresso-ch** [comment]
Thanks I had missed that in the controller in the branch master. Sorry for double issue...

**Comment by Mesuva** [comment]
No problem at all!
