### ISSUE TITLE
Optional fields during checkout

### ISSUE THREAD

**Issue by f6cm** [concretecms-community-store/community_store#755]
Hi, 

Is there a way to make some fields optional during checkout ?
I have one store that doesn't need shipping, and I would like to make the address field optional (or make it completely disappear if it's easier).

Thank you for this amazing plug in !

**Comment by Mesuva** [comment]
If none of the products in a cart have shipping required for them (i.e. 'Product is Shippable' is set to Tes), it shouldn't offer the shipping fields at all.
