### ISSUE TITLE
Undefined variable $product

### ISSUE THREAD

**Issue by shitehawke** [concretecms-community-store/community_store#756]
Hi, fresh install on Concrete 9.1.3, using community store V 2.4.8.5. PHP 8.2
When trying to edit the product template via Page Types > Output, I get an "Undefined variable $product" warning on line 7 of the view.php file if (is_object($product) && $product->isActive()) {

Is this a php8 bug?

**Comment by Mesuva** [comment]
Yes, a PHP8 bug. 
Try this quick fix here: https://github.com/concretecms-community-store/community_store/commit/1b2af129ecfd7986da6a9652c21df8fce03ce8fa

**Comment by shitehawke** [comment]
That's perfect, thanks!

**Comment by mlocati** [comment]
This issue can be closed, isn't it?
