### ISSUE TITLE
New payment method: BCC PayWay

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#768]
I'm creating a new payment method, which uses the PayNow service offered by a group of Italian banks called BCC (Banche di Credito Cooperativo).

In order to do that, I first created a generic PHP library (https://github.com/mlocati/PayWay), and I'm creating the plugin for Community Store (which uses that generic library) at https://github.com/mlocati/community_store_bcc_payway (it's still a work in progress, but I'm at a good point).

What about creating a new repo under https://github.com/concretecms-community-store instead of https://github.com/mlocati/community_store_bcc_payway?

Maybe something like https://github.com/concretecms-community-store/community_store_bcc_payway ?

**Comment by Mesuva** [comment]
I've created this repo, and have given you admin access - so I believe you have full control to manage this as you see fit.
