### ISSUE TITLE
product_modal element is broken on PHP 8+

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#792]
See https://github.com/concretecms-community-store/community_store/pull/783 for details

**Comment by Mesuva** [comment]
I decided to remove this feature, as:
- it's difficult to maintain
- I think there are further existing bugs
- I don't think it's a great feature
- I can't think of anyone ever using it

**Comment by mlocati** [comment]
Closed by 2e0e4a44fab73302fcbb97e82759f4f9d7609cb3
