### ISSUE TITLE
Meaning of "Reverse a payment"

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#805]
In order to correctly translate strings, I'd need a clarification: "reverse" means "cancel", right?

So, are these ok?

1. "Order Payment Reversed" means "The payment of the order has been canceled"
2. "Are you sure you wish to reverse this payment?" means "Are you sure you wish to cancel this payment?"
3. "Order Refund Reversed" means "The refund of the order has been canceled"
4. "Are you sure you wish to reverse this refund?" means "Are you sure you wish to cancel this refund?"
5. "Order Cancellation Reversed" means "The cancellation of the order has been canceled"
6. "Are you sure you wish to reverse this cancellation?" means "Are you sure you wish to cancel this cancellation?"
7. "Reverse Cancellation" means "Cancel Cancellation"
8. "reverse" means "cancel" ([here](https://github.com/concretecms-community-store/community_store/blob/master/single_pages/dashboard/store/orders.php#L476) and [here](https://github.com/concretecms-community-store/community_store/blob/master/single_pages/dashboard/store/orders.php#L500))

**Comment by Mesuva** [comment]
I think the word 'reverse' might be better explained as 'undone'. As it you 'undo' an action.
So:

"Order Payment Reversed" means "The payment of the order has been undone"
"Are you sure you wish to reverse this payment?" means "Are you sure you wish to undo this payment?"
"Order Refund Reversed" means "The refund of the order has been undone"
"Are you sure you wish to reverse this refund?" means "Are you sure you wish to undo this refund?"
"Order Cancellation Reversed" means "The cancellation of the order has been undone"
"Are you sure you wish to reverse this cancellation?" means "Are you sure you wish to undo this cancellation?"
"Reverse Cancellation" means "Undo Cancellation"

I just don't know how well the word 'undone' translates from English into other languages!

**Comment by mlocati** [comment]
I still don't understand the meaning of "reverse a payment".

For example: a customer submits and he pays an order. Then I check that I'm actually out of stock for the ordered items, so I refund him.
Isn't this a "refund"? How's it different from "reversing a payment"? When do we "reverse a payment"?

**Comment by Mesuva** [comment]
It's very subtle:
It's when an order is placed, but it's not immediately paid for (i.e. an invoice payment)
You then as an admin go in and mark the order as paid, manually.
It's when you reverse _that_ action, it's reversing the payment. 

This is slightly different to a refund, in that when you do one of those you end up with record of a payment, and then the record of a refund (with a reason). This is different to reversing a payment, where it's more like you've made a mistake and marked an invoice as paid when you shouldn't have.

**Comment by mlocati** [comment]
That's clear, now! Thank you, Ryan!
