### ISSUE TITLE
Concrete Version - 9.2.1 & Store Version 2.6 - Filter by Brand / Manufacturer "Doctrine \ DBAL \ Exception \ DriverException" Error

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store#817]
https://www.mytinytown.com/store-products-manufacturer/products-mdi-electrical-relays-switches

When you select any filter you get an error. But only when a "Filter by Brand / Manufacturer" is selected in the Edit Product List.

`An exception occurred while executing 'SELECT p.pID FROM CommunityStoreProducts p LEFT JOIN CommunityStoreProductSearchIndexAttributes csi ON p.pID = csi.pID WHERE (ak_product_type REGEXP ?) AND (pManufacturer = ?) AND (pActive = 1) GROUP BY p.pID, p.pName, p.pPrice, p.pActive, p.pDateAdded ORDER BY pName desc' with params ["(^|\n)Mercury Relays($|\n)"]: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens`

**Comment by Mesuva** [comment]
This is an odd one, I was pretty sure we'd resolved this quite a few versions ago.
Will try to look at this soon.

**Comment by Mesuva** [comment]
Try this update here:
https://github.com/concretecms-community-store/community_store/commit/0ba3d8e2b860d4d95310ac609b29bcded671cb12#diff-75b84fc065a9b0519db02c3ea73533feb031576c96920161a47ad141586c6182L398

**Comment by mdius** [comment]
This fixed worked perfectly! Thank you.
