### ISSUE TITLE
Ask users to accept the privacy policy when submitting an order?

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#821]
When users submit an order, they give their personal details to the seller.

And that requires that the seller tells the customer what he's going to do with this personal data.

Is there a way to add a (required) checkbox when customers submit orders? Something like this

[ ] By submitting your order, you accept [our privacy policy](https://example.org)

**Comment by Mesuva** [comment]
A custom attribute under Order attributes, in the 'Other Customer Choices' set should prompt within the checkout steps. And it can be set to be required as well. The actual link might not be possible, but you could refer to 'our privacy policy as linked in our footer'.

**Comment by mlocati** [comment]
I don't think there's a way to force users to tick a checkbox attribute.

Since I think it's a pretty common requirements, would you accept a PR that implements the following:

1. add a new option in the `/dashboard/store/settings#settings-orders` dashboard page: "ask users to accept the privacy policy"
2. if the above is checked, site operators must also provide the page (or external URL) of this privacy policy
3. if the option is checked, customers must check this checkbox when they submit their personal data.

**Comment by mlocati** [comment]
> the 'Required in checkout' setting on an attribute

Is these such a feature? Wow, I wasn't aware of it

**Comment by mlocati** [comment]
> the 'Required in checkout' setting on an attribute

I've just tried this:

![immagine](https://github.com/concretecms-community-store/community_store/assets/928116/0fe751d0-79d9-47fc-b1a0-3f52d7fb8f9e)

The checkbox is displayed to the customers, but they can proceed without checking it:


https://github.com/concretecms-community-store/community_store/assets/928116/4821d53f-0997-4c4e-a8bf-8f2e8d38b68a

**Comment by Mesuva** [comment]
Yes, that _used_ to work, I'm going to take a look at what may have changed.

**Comment by mlocati** [comment]
The problem is in `single_pages/checkout.php`.

We have:

```php
$fieldoutput = $cv->renderControl();
if ($ak->isRequired()) {
    $fieldoutput = str_replace('<input', '<input required ', $fieldoutput);
    $fieldoutput = str_replace('<select', '<select required ', $fieldoutput);
}
echo $fieldoutput;
```

But we should have something like this:

```php
ob_start();
$fieldoutput1 = $cv->renderControl();
$fieldoutput2 = ob_get_contents();
ob_end_clean();
$fieldoutput = $fieldoutput1 === null ? $fieldoutput2 : $fieldoutput1;
if ($ak->isRequired()) {
    $fieldoutput = str_replace('<input', '<input required ', $fieldoutput);
    $fieldoutput = str_replace('<select', '<select required ', $fieldoutput);
}
echo $fieldoutput;
```

**Comment by mlocati** [comment]
For anyone reading this: I've created package that provides a boolean (checkbox) attribute whose description can be a Rich Text, so that for example it can be something like this:

[ ] By submitting this order I accept the terms [described here](https://www.example.org)

You can find it here: https://github.com/concrete5-community/boolean_rich

**Comment by Mesuva** [comment]
I reckon that would be very handy for other reasons, like on normal (Express) forms

**Comment by mlocati** [comment]
I've submitted the boolean_rich addon to the marketplace and it has just been approved: see https://marketplace.concretecms.com/marketplace/addons/boolean-rich-text/

Of course you can still install it via composer:

```json
{
    "require": {
        "concrete5-community/boolean_rich": "^1"
    }
}
```
