### ISSUE TITLE
error with payments (Call to a member function getPackageHandle() on null)

### ISSUE THREAD

**Issue by baxterdmutt** [concretecms-community-store/community_store#823]
I'm getting this error. Ive tried removing all the packages and then reinstalling. Even without a payment method, the error continues: This started after upgrading to 9.2.2

> Call to a member function getPackageHandle() on null
> 27
> Error 
> /usr/local/share/concrete5/concrete-cms-9.2.2/packages/community_store/src/CommunityStore/Payment/Method.php202
> 26
> Concrete\Package\CommunityStore\Src\CommunityStore\Payment\Method setMethodController
> /usr/local/share/concrete5/concrete-cms-9.2.2/packages/community_store/src/CommunityStore/Payment/Method.php243
> 25
> Concrete\Package\CommunityStore\Src\CommunityStore\Payment\Method getMethods
> /usr/local/share/concrete5/concrete-cms-9.2.2/packages/community_store/controllers/single_page/dashboard/store/settings.php43

**Comment by Mesuva** [comment]
You may need to manually update src/CommunityStore/Payment/Method.php to https://raw.githubusercontent.com/concretecms-community-store/community_store/249eb427436cac46563dbceefbf9867256935f31/src/CommunityStore/Payment/Method.php
to resolve this, as @mlocati has kindly addressed this issue

**Comment by baxterdmutt** [comment]
Strangely enough it went away on its own. I may have reinstalled community store. But honestly I can’t recall what changed. As I said in another issue, the update from 9.1.3 to 9.2.1 and finally 9.2.2 did something terrible to the store on 2 servers I run. I couldn’t uninstall any store package so I needed to go into all the ones related to the store and remove them manually and reinstall. I have been unfortunate in the upgrades from 8 and into the 9s. Hopefully that’s all behind me now.  Thanks
