### ISSUE TITLE
Order Notes

### ISSUE THREAD

**Issue by SB1955** [concretecms-community-store/community_store#835]
When enabling ‘Order notes’ in ‘Settings/Cart and Checkout’ the note box to allow content appears on first page. However it doesn’t show on the next checkout pages?
Have I missed something?

CMS version: 9.2.4. CS version: 2.6.2

Note: I've changed 'Notes' to 'Reference Number'. See attached.
![Notes-Show](https://github.com/concretecms-community-store/community_store/assets/88653548/99bf99ca-9b32-4a17-b51a-d365ffe559a3)

![No-Notes](https://github.com/concretecms-community-store/community_store/assets/88653548/88ee7bc8-3498-4177-85e1-1c98bc795051)

**Comment by SB1955** [comment]
Fixed by using a different method. Added 'Booking Reference' and 'Terms' under 'Orders/Attributes' as discussed with issue:
https://github.com/concretecms-community-store/community_store/issues/821.
So getting close to what I want.

**Comment by Mesuva** [comment]
I'm surprised that the order notes aren't displaying on the summary. Is this a brand new install, or one you've upgraded?

**Comment by SB1955** [comment]
Local dev site upgraded, could that be the issue?

**Comment by SB1955** [comment]
REF: Mac mini M2 with CMS 9.2.4 - PHP 8.2.4 - Store 2.6.3.

**Comment by SB1955** [comment]
The 'ob_start();' etc is not in the latest store release 'single_pages/checkout.php'. So I copied and pasted issue (#821) into my 'application/single_pages/checkout.php' and so far all works.

**Comment by Mesuva** [comment]
I was just thinking that maybe you had an older checkout single page template that needed updating.

**Comment by SB1955** [comment]
No. What I tend to do is check to see what the difference if between the old and new templates code, then change if needed (as well as anything else).

**Comment by SB1955** [comment]
Okay. Fresh install with full 'Atomik'. Store 2.6.3 and ticked 'Enable order notes', still not showing after first page in checkout?

**Comment by Mesuva** [comment]
Try this fix here: https://github.com/concretecms-community-store/community_store/commit/e3f5ade241b3c1cc7e35129d3f1fa90ebaa66811

**Comment by SB1955** [comment]
Thanks. That fix works for me.
