### ISSUE TITLE
Typo in cart_list.php

### ISSUE THREAD

**Issue by SB1955** [concretecms-community-store/community_store#843]
Found a typo in: store/elements/cart_list.php.

On line 21 we have <th class="text-right text-end"=">

Removed the offending equal sign and double quote. See attached.
![Source](https://github.com/concretecms-community-store/community_store/assets/88653548/0d39e46b-cc04-4f8c-b59a-a6ddf380df0d)
![Line-Mod](https://github.com/concretecms-community-store/community_store/assets/88653548/93fed176-c2eb-4973-a654-7b0d0f9e271b)

**Comment by Mesuva** [comment]
Awesome, thank you
