### ISSUE TITLE
Switch from magnific popup to photoswipe ?

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#849]
magnific popup seems rather abandoned.

What about switching to something else (like for example [PhotoSwipe](https://photoswipe.com/)) that supports gestures (zoom, swipe, ...)?

**Comment by Mesuva** [comment]
I'm certainly open to alternatives.

Magnific has been pretty reliable over the years, I've just not had a reason to swap it out myself, no-one has every mentioned it!

**Comment by mlocati** [comment]
I created an ecommerce website for a friend of mine, and her customers use mainly mobile phones.

Browsing the images on such devices could be much better...
For example, compare the user experience of these two galleries on a mobile phone:
- https://www.sandroferronecantu.it/products/maglia-morbida-spacchetti-turchese
- https://photoswipe.com/

The former allows pinch-to-zoom, swipe, and much more 😉

**Comment by mlocati** [comment]
>  - https://www.sandroferronecantu.it/products/maglia-morbida-spacchetti-turchese

Not it's much better 😉

**Comment by Mesuva** [comment]
Yes, much better!

**Comment by Mesuva** [comment]
By the way @mlocati, I'm thinking about creating a new release this week - do you have any other changes you are working on, or is this good timing?

**Comment by mlocati** [comment]
No other pending changes, Ryan.

Thanks for your great work!

**Comment by mlocati** [comment]
>> do you have any other changes you are working on, or is this good timing?
>
> No other pending changes, Ryan.

I guess I was wrong 😉
