### ISSUE TITLE
New payment method: Nexi

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#863]
I'm going to create a new payment method, which uses services offered by [Nexi](https://www.nexi.it/) (a provider that's widely used here in Italy).

What about creating a new repo for it? Something like https://github.com/concretecms-community-store/community_store_nexi maybe?

**Comment by Mesuva** [comment]
Done - you should have full access to that new repo

**Comment by mlocati** [comment]
Thanks!
