### ISSUE TITLE
Add dashboard page to list details of payments?

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#877]
I developed two payment methods ([this](https://github.com/concretecms-community-store/community_store_bcc_payway) and [this](https://github.com/concretecms-community-store/community_store_nexi)) that store the details of the payment messages associated to every order (e.g. the data sent to the payment servers and the data received back from them).

At the moment, the only way to check these messages is by accessing the database directly.

What about adding to Community Store a new dashboard page where users can see the details of such messages?

I was thinking about something like this:

1. in the on_start method of packages providing payment methods, we could introduce some code like this:
   ```php
   use Concrete\Package\CommunityStore\Src\CommunityStore\Payment\LogProviderFactory;
   
   public funciton on_start()
   {
       $this->app->extend(LogProviderFactory::class, function(LogProviderFactory $factory) {
           $factory->registerProvider($this->app->make(ThisPaymentMethodLogProvider::class));
           return $factory;
       });
   }
   ```
2. the new dashboard page would query the registered log providers, displaying the details of the messages (by date or for a specific order)
3. in the details page of an order, we could add a link to that new dashboard page, passing it the order we want the log for

If that's ok, I can create a pull request that implements this new feature.

**Comment by mlocati** [comment]
The log providers could implement an interface like this:

```php
<?php

declare(strict_types=1);

namespace Concrete\Package\CommunityStore\Src\CommunityStore\Payment;

use Concrete\Package\CommunityStore\Src\CommunityStore\Order\Order;
use DateTimeInterface;

interface LogProvider
{
    /**
     * Get the handle that uniquely identifies this log provider.
     */
    public function getHandle(): string;

    /**
     * Get the display name of this log provider.
     */
    public function getName(): string;

    /**
     * Find the log entries in the specified date/time range.
     *
     * @return \Concrete\Package\CommunityStore\Src\CommunityStore\Payment\LogEntry[]
     */
    public function findByDate(DateTimeInterface $from, DateTimeInterface $to): array;

    /**
     * Find the log entries associated to a specific order.
     *
     * @return \Concrete\Package\CommunityStore\Src\CommunityStore\Payment\LogEntry[]
     */
    public function findByOrder(Order $order): array;
}
```

**Comment by Mesuva** [comment]
Is the main benefit of this that it's a different log 'channel'?
Im just looking to understand why we'd use this, and not just standard logs.

**Comment by Mesuva** [comment]
That makes sense. Would you then suggest that once this is place that all payment gateways should be adjusted to work with logs the same way?

**Comment by mlocati** [comment]
That's just an opt-in feature, which requires that the payment gateways store the data of each step.

Of course that'd be nice.

And here's an example of a session of the code I'm developing:

- if at least one payment method implements this feature, in the order details page we have this new button:
   ![immagine](https://github.com/concretecms-community-store/community_store/assets/928116/c623da90-77f3-40ff-9a66-4d00f296979a)
- by clicking it, we go to this new dashboard page:
  ![immagine](https://github.com/concretecms-community-store/community_store/assets/928116/3d576068-d8b6-480f-adcc-b23cad57530d)
- if we click on the View button, we see the details of the data sent/received:
   ![immagine](https://github.com/concretecms-community-store/community_store/assets/928116/181d3681-e9e5-47da-af66-b5cc25c9bfea)

**Comment by Mesuva** [comment]
That's very cool - I see what you're looking to do here.
With there being so many different ways that payment gateways work, each one has their own quirks and sometimes fiddly ways to debug.

**Comment by mlocati** [comment]
And here it is: #878
