### ISSUE TITLE
Order sent by the "on_community_store_order" event doesn't have orderItems initialized

### ISSUE THREAD

**Issue by Quentindeve** [concretecms-community-store/community_store#881]
# What went wrong

I did a simple package for ConcreteCMS that subscribes to the "on_community_store_order" event. The function called on trigger is here:
```php
public function orderPlaced(OrderEvent $event) {
        $order = $event->getOrder();
        $dataToSend = $order->getOrderItems();
        Log::addInfo("Order: " . $dataToSend);
    } 
```

However, the array returned by this Order is empty. Moreover, fetching it with Order::getByID(int $id) doesn't solve the issue. Therefore this code snippet doesn't work too:

```php
public function orderPlaced(OrderEvent $event) {
        $order = $event->getOrder();
        $order = Order::getByID($order->getOrderID()); // This is supposed to fetch all related data with the ORM, so to load Order::$orderItems
        $dataToSend = new OrderTransform($order);
        Log::addInfo("Order: " . $dataToSend);
    }
```

**Comment by Mesuva** [comment]
That's odd - I just tried logging some things from an order using that event, on version 2.6.5, and it worked as expected.

I tried something like this:
<img width="614" alt="Screenshot 2024-06-10 at 09 20 07" src="https://github.com/concretecms-community-store/community_store/assets/1079600/9ca64b74-f37c-4413-8389-239c0d3cac7f">

And I had both the order ID, and the name of the product I had in the order output in the logs.

Whatever Community Store version are you running?

**Comment by Quentindeve** [comment]
I use CS version 2.6.4.

**Comment by Mesuva** [comment]
Is it the same for the Invoice method, as for other payment methods?

**Comment by Quentindeve** [comment]
Yes, the issue is unrelated to payment methods unfortunately

**Comment by Mesuva** [comment]
How strange.

If you want to send me the add-on you're working on I'm happy to take a look. 
Or if you've got a development environment to debug, happy to look at that too.
Shoot a message to ryan@mesuva.co.uk

**Comment by Quentindeve** [comment]
Done !

**Comment by Quentindeve** [comment]
After few emails with @Mesuva the solution was found:

- Go to ``/index.php/dashboard/system/environment/entities``
- If you are on development server enable the ``Doctrine development mode``
- Click on the bottom left button ``Refresh entities``

It solved the issue on my side !
