### ISSUE TITLE
Setting Product::pQtyUnlim to 1 in Entity ends up being 0 in Database

### ISSUE THREAD

**Issue by QuentindevePro** [concretecms-community-store/community_store#885]
I have a simple code that creates a Product entity and then persists it to database:
```php
function createCsProduct(ImportProduits $produit, EntityManager $em)
{
    $csProduct = new Product();
    $csProduct->setName($produit->getNom_Produit());
    $csProduct->setSKU($produit->getReference());
    $csProduct->setBarcode($produit->getEAN13());
    $csProduct->setPrice($produit->getPrix());
    $csProduct->setIsActive(true);
    $csProduct->setSalePrice($produit->getPrix());
    $csProduct->setQty(1000);
    $csProduct->setCustomerPrice(false);
    $csProduct->setQuantityPrice(false);
    $csProduct->setIsFeatured(false);
    $csProduct->setNoQty(true);
    $csProduct->setAllowDecimalQty(false);
    $csProduct->setIsTaxable(false);
    $csProduct->setImageID(0);
    $csProduct->setIsShippable(true);
    $csProduct->setCreatesUserAccount(false);
    $csProduct->setAutoCheckout(false);
    $csProduct->setIsExclusive(false);
    $csProduct->setNotificationEmails(false);
    $csProduct->setDateAdded(new \DateTime());
    $csProduct->setHasVariations(true);
    $csProduct->setIsUnlimited(true);

    $group = $em->getRepository(Group::class)->findOneBy(["groupName" => $produit->getCategorie()]);
    ProductGroup::add($csProduct, $group->getID());
    $csProduct->save();
    $csProduct->generatePage();
    return $csProduct;
}
```

However, even with ``$csProduct->setIsUnlimited(true)`` called, the resulting record in database ends up with ``pQtyUnlim`` on zero. I have the same issue with ``ProductVariation::setVariationIsUnlimited(true)``.

**Comment by Mesuva** [comment]
I just tried this myself, and my unlimited box ended up checked

But I had to change this to:
`$csProduct->setHasVariations(false);`

What _is_ missing is a bunch of sensible defaults for products, so you don't have to specifically set a bunch of options you aren't interested in. I'm just about to push up a fix for that.

**Comment by Mesuva** [comment]
Try applying this, then doing a doctrine refresh and cache clear, you should be able to then omit lots of these setters:

https://github.com/concretecms-community-store/community_store/commit/c12436c7a30033dcbea5e9402e28b57134f861f4

**Comment by Mesuva** [comment]
It might depend on what you are wanting to do in terms of where the quantities are actually managed.

In the store Settings, there's an option here:

![Screenshot 2024-07-01 at 13 37 36](https://github.com/concretecms-community-store/community_store/assets/1079600/9c88128d-ff8d-47bb-a9c7-c36782de4b49)

Perhaps try setting that to No, and then in your API call setting setHasVariations to true.

**Comment by QuentindevePro** [comment]
I see. Thanks for your reactivity !
