### ISSUE TITLE
parentPageId not used in install ?

### ISSUE THREAD

**Issue by MC59550** [concretecms-community-store/community_store#892]
Hello,

It seems that $parentPageId is not used in :
https://github.com/concretecms-community-store/community_store/blob/9df15d973e54949c906661877e7d2ffab88836f3/src/CommunityStore/Utilities/Installer.php#L405

Perhaps it's more complicated because of the slug '/products' used in some places in the code .

PS 1 : i've just seen that and have no time this week to go deeper in the code so please excuse me if I'm wrong 

PS 2  : Context : I've found that beacause I was exploring the way to install in CLI and I wasn't able to find the documentation for install in CLI.

**Comment by Mesuva** [comment]
You're quite right - this bit was overlooked when the installed was recently reworked.
I've pushed up a fix, so this will be in the next release.
https://github.com/concretecms-community-store/community_store/commit/1ef891071f787dda320fc0cc72285cccd8c5ed22

Making this selection via the CLI might not be possible though, it'll just set to the default I think.
