### ISSUE TITLE
custom attributes in emails

### ISSUE THREAD

**Issue by fatcatsanonymous** [concretecms-community-store/community_store#893]
Custom attributes to the order form in the community store backend work fine on the checkout and confirm pages, but do not show up in the emails generated by new_order_notification.php or order_receipt.php:
Script in Email:
`<?php if (!empty($orderChoicesAttList)) { ?>
            <tr>
                <td colspan="2">
                    <h3><?= t("Other Choices")?></h3>
                    <?php foreach ($orderChoicesAttList as $ak) {
                        $orderOtherAtt = $order->getAttributeValueObject($ak->getAttributeKeyHandle());
                        if ($orderOtherAtt) {
                            $attvalue = trim($orderOtherAtt->getValue('displaySanitized', 'display'));
                            if ($attvalue) { ?>
                                <strong><?= $ak->getAttributeKeyDisplayName() ?></strong>
                                <p><?= str_replace("\r\n", "<br>", $attvalue); ?></p>
                            <?php }
                        }?>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>`

**Comment by Mesuva** [comment]
That's a strange one as I'm sure others are using this.
What version of Community Store?

I'll give this a test in a few moments

**Comment by mnakalay** [comment]
Ryan, I tested that order attribute issue in CS, and it works normally. I added a text and checkbox attribute and got them both in the email.
Using latest version.

**Comment by fatcatsanonymous** [comment]
Hi, Thanks for your replies and for testing this. We're using version 2.6.0. I will try updating to 2.7.1 and see if this helps. We're not using any payment methods - it is being used as an order system only.

**Comment by fatcatsanonymous** [comment]
I've tested another 2.6.0 set up and the custom attributes work there so I am assuming this is not a community store issue but rather has to do with custom scripts. Thanks for your help.
